export interface DomainNode {
  id: string;
  title: string;
  description: string;
  psychology: string;
  philosophy: string;
  science: string;
  lifehack: string;
  group?: string; // Do kolorowania
}

export interface DomainLink {
  id: string;
  from: string;
  to: string;
  type: 'flow' | 'awareness' | 'override' | 'conflict';
  label: string;
  direction?: 'to' | 'from' | 'both';
  description: string;
  psychology: string;
  philosophy: string;
  science: string;
  lifehack: string;
}

export const MIKRO_NODES: DomainNode[] = [
  {
    id: "m1",
    title: "Jaźń / Obserwator",
    description: "Zdolność do zatrzymania się i obserwowania tego, co czujesz i myślisz, zamiast ślepo za tym podążać. To punkt, z którego patrzysz na siebie z boku.",
    psychology: "Terapia Akceptacji i Zaangażowania (ACT) nazywa to stanem 'Ja-jako-kontekst'. To stabilna perspektywa, z której zauważasz swoje myśli i emocje, ale nie utożsamiasz się z nimi.",
    philosophy: "W buddyzmie odpowiada to pojęciu uważności i braku stałego ego (Anatta) – jesteśmy obserwatorem ciągle zmieniającego się strumienia. Edmund Husserl opisywał to jako 'czyste ego'.",
    science: "Zdolność do introspekcji zależy od Sieci Wzbudzeń Podstawowych (DMN - Default Mode Network) w mózgu.",
    lifehack: "Defuzja poznawcza. Zamiast 'Jestem wściekły', powiedz 'Zauważam w sobie uczucie wściekłości'. To tworzy realny dystans bez bycia śmiesznym.",
    group: 'awareness'
  },
  {
    id: "m2",
    title: "Wola / Funkcja Wykonawcza",
    description: "Zdolność do powstrzymania się przed natychmiastowym działaniem. To moment, w którym świadomie wybierasz, co zrobisz, zamiast reagować automatycznie.",
    psychology: "Psychologia poznawcza bada to jako funkcje wykonawcze, czyli naszą samokontrolę. Zgodnie z badaniami (tzw. ego depletion), samokontrola działa trochę jak mięsień.",
    philosophy: "Stoik Epiktet nazywał to prohairesis – moralnym wyborem. Uważał, że to jedyna rzecz na świecie, która jest w 100% pod naszą kontrolą.",
    science: "Ośrodkiem decyzyjnym jest kora przedczołowa (PFC). Jej działanie wymaga ogromnych ilości energii (glukozy i tlenu), żeby skutecznie wysyłać sygnały hamujące do układu limbicznego.",
    lifehack: "Wprowadź gap practice. Między zewnętrznym bodźcem a Twoją reakcją wymuś 5 sekund fizycznej pauzy. Przenosi to przetwarzanie do kory czołowej.",
    group: 'executive'
  },
  {
    id: "m3",
    title: "Myśli",
    description: "Ciągły wewnętrzny głos, który komentuje, ocenia i przewiduje wszystko dookoła. To po prostu hipotezy naszego mózgu, a nie obiektywne fakty.",
    psychology: "Terapia Poznawczo-Behawioralna (CBT) uczy, że nasze umysły często tworzą błędy poznawcze – katastrofizują lub próbują czytać w myślach innych.",
    philosophy: "Immanuel Kant udowodnił, że nigdy nie widzimy rzeczywistości takiej, jaka jest – zawsze filtrujemy ją przez nasze z góry ukształtowane kategorie rozumu.",
    science: "Myślenie to aktywność elektryczna kory mózgowej, widoczna w badaniach EEG jako fale Beta (logika) lub Gamma (łączenie informacji).",
    lifehack: "Złap myśl, która sprawia Ci ból i zadaj jedno bezlitosne pytanie: 'Czy mam 100% pewności, że to obiektywna prawda?'.",
    group: 'cognitive'
  },
  {
    id: "m4",
    title: "Uczucia",
    description: "Fizyczne sygnały płynące z ciała, informujące nas o bezpieczeństwie, stratach lub naruszeniu naszych granic. Wrodzony system wczesnego ostrzegania.",
    psychology: "Terapie takie jak EFT czy DBT kładą ogromny nacisk na emocje jako cenne informacje. Udawanie, że emocji nie ma, prowadzi do fizycznego rozregulowania ciała.",
    philosophy: "David Hume twierdził, że nasz rozum to tylko niewolnik namiętności – najpierw czujemy, a dopiero potem dorabiamy do tego racjonalne wytłumaczenia.",
    science: "Emocje wyzwalają się w ciele migdałowatym w ułamku sekundy, zanim zdążymy je świadomie przemyśleć.",
    lifehack: "Namierz fizyczną lokację. Emocja bez lokalizacji to abstrakcyjny lęk. Zidentyfikuj napięcie bezpośrednio w ciele i zacznij mechanicznie je rozluźniać.",
    group: 'emotional'
  },
  {
    id: "m5",
    title: "Impulsy",
    description: "Bardzo stare, silne pragnienia natychmiastowej nagrody lub ucieczki od bólu. Gwałtowne chęci zjedzenia czegoś słodkiego czy ucieczki od trudnej rozmowy.",
    psychology: "W psychoanalizie Freuda impulsy to 'Id' – dzika część nas domagająca się przyjemności tu i teraz.",
    philosophy: "Thomas Hobbes uważał, że człowiek z natury kieruje się tylko dwoma rzeczami: ucieczką od bólu i dążeniem do przyjemności.",
    science: "Impulsami steruje dopamina. Szlak nagrody zalewa mózg tym neuroprzekaźnikiem, wywołując agresywną chęć zdobycia nagrody.",
    lifehack: "Zastosuj 'Urge Surfing'. Gdy uderzy nagły impuls, wizualizuj go jako falę, która podnosi się, a następnie samoistnie opada w ciągu 90 do 180 sekund.",
    group: 'emotional'
  },
  {
    id: "m6",
    title: "Zachowania",
    description: "To, co fizycznie robimy. Jedyny punkt, w którym realnie wpływamy na otaczający nas świat.",
    psychology: "Behawioryści (np. B.F. Skinner) udowodnili, że to, co robimy, zależy bezpośrednio od nagród i kar. Terapia ACT uczy z kolei działania zgodnego z wartościami.",
    philosophy: "Pragmatyzm (William James) głosi, że nasze intencje i myśli same w sobie nie mają znaczenia – liczą się nasze widoczne, konkretne czyny.",
    science: "Gdy powtarzamy czynność setki razy, zwoje podstawy przejmują nad nią pałeczkę, tworząc nawyk, aby zaoszczędzić energię mózgu.",
    lifehack: "Podczepianie nawyków. Zamiast budować nawyk od zera, doklej go do czegoś, co i tak robisz codziennie (np. 'po umyciu zębów').",
    group: 'executive'
  },
  {
    id: "m7",
    title: "Wrażenia z ciała",
    description: "Surowe sygnały płynące z naszych mięśni, narządów wewnętrznych i oddechu. Sposób, w jaki ciało z nami rozmawia.",
    psychology: "Terapie skoncentrowane na ciele opierają się na fakcie, że ciało pamięta stres. Nierozwiązana trauma objawia się jako płytki oddech czy napięcie barków.",
    philosophy: "Maurice Merleau-Ponty twierdził, że nie 'mamy' ciała jak narzędzia – my 'jesteśmy' ciałem. To nasz podstawowy punkt styku ze światem.",
    science: "Kora wyspy bezustannie monitoruje narządy wewnętrzne. Teoria poliwagalna tłumaczy, jak nasz układ nerwowy ocenia bezpieczeństwo i dostraja napięcie.",
    lifehack: "Reset wagalny. Wykonaj wydech trwający dwukrotnie dłużej niż wdech. To mechanicznie obniża tętno i wyłącza reakcję stresową.",
    group: 'physiological'
  },
  {
    id: "m8",
    title: "Bieżące Przekonania",
    description: "Filtry, przez które patrzymy na świat. Milczące założenia o tym, jacy jesteśmy my sami i jacy są inni ludzie.",
    psychology: "Albert Ellis dowodził, że sztywne, bezwzględne przekonania ('muszę', 'zawsze') są głównym źródłem naszych problemów psychicznych.",
    philosophy: "Filozoficzny konstruktywizm opiera się na założeniu, że nigdy nie widzimy obiektywnego świata – my go stale konstruujemy w oparciu o to, w co już wierzymy.",
    science: "Kiedy w coś długo wierzymy, połączenia między neuronami wzmacniają się (reguła Hebba). Mózg wybiera starą ścieżkę, bo to oszczędza energię.",
    lifehack: "Gdy wyciągasz negatywne wnioski, zapytaj: 'Z jakiego milczącego założenia o świecie właśnie wyszedłem, że tak bardzo mnie to zabolało?'.",
    group: 'cognitive'
  },
  {
    id: "m9",
    title: "Czynniki Zewnętrzne",
    description: "Bezpośrednie otoczenie: Twój pokój, temperatura, przedmioty i ludzie w zasięgu wzroku.",
    psychology: "Kurt Lewin sformułował równanie: nasze zachowanie to zawsze wypadkowa naszej osoby i naszego środowiska. Ulegniesz, jeśli przebywasz w złym otoczeniu.",
    philosophy: "Determinizm uczy, że warunki fizyczne kształtują nie tylko to, co robimy, ale też to, jak myślimy.",
    science: "Światło, temperatura i dźwięk wywołują zmiany biochemiczne. Złe oświetlenie czy podwyższony poziom CO2 radykalnie obniżają sprawność.",
    lifehack: "Optymalizacja otoczenia. Schowaj rozpraszacze do szafy. Zrób tak, by właściwe zachowanie było najłatwiejszą opcją.",
    group: 'environmental'
  },
  {
    id: "m10",
    title: "Język i Dialog",
    description: "Słowa, jakich używasz do nazywania emocji. Twój wewnętrzny słownik, z którego układasz historię o swoim życiu.",
    psychology: "Rozwój cichej mowy wewnętrznej. To, jak do siebie mówisz (ostro czy łagodnie), potężnie wpływa na Twój stan w momentach stresu.",
    philosophy: "Ludwig Wittgenstein: 'Granice mojego języka oznaczają granice mojego świata'. Bez pojęć jesteśmy uwięzieni w chaosie odczuć.",
    science: "Precyzyjne określanie emocji aktywuje obszary językowe mózgu i fizjologicznie hamuje układ limbiczny (tzw. chłodzenie emocji).",
    lifehack: "Nazywaj emocje precyzyjnie. Im bogatsze słownictwo, tym niższy stres.",
    group: 'cognitive'
  },
  {
    id: "m11",
    title: "Biochemia i Zasoby Metaboliczne",
    description: "Poziom sił witalnych, sen, nawodnienie oraz krążąca mieszanka hormonów i neuroprzekaźników (dopamina, kortyzol, kofeina). Biologiczne paliwo i regulator nastroju oraz samokontroli.",
    psychology: "Brak energii i odchylenia biochemiczne drastycznie obniżają odporność na lęk i złość, spychając umysł do odruchów nawykowych.",
    philosophy: "Materializm biologiczny – racjonalność i duch nie działają w próżni, lecz bezwzględnie wymagają sprawnego nośnika metabolicznego.",
    science: "Kora przedczołowa wymaga glukozy i tlenu, a poziom kortyzolu i dopaminy dyktuje próg wzbudzenia ciała migdałowatego.",
    lifehack: "Zasada HALT i audyt biochemiczny: nie podejmuj trudnych decyzji na głodzie i zmęczeniu, a przy przewlekłym spadku zrób badania krwi.",
    group: 'physiological'
  },
  {
    id: "m13",
    title: "Rezonans Interpersonalny",
    description: "Zdolność układu nerwowego do sprzęgania się z układem innej osoby w celu wspólnego uspokojenia.",
    psychology: "Neurobiologia interpersonalna dowodzi, że bardzo trudno wyciszyć potężny stres w pojedynkę. Potrzebujemy bezpiecznej, spokojnej obecności (koregulacji).",
    philosophy: "Martin Buber i relacja 'Ja-Ty'. Autentyczne bycie z drugą osobą całkowicie transformuje nasze przeżywanie świata.",
    science: "Neurony lustrzane i nerw błędny bezustannie skanują twarz i ton głosu rozmówcy, decydując o trybie walki/ucieczki lub odpoczynku.",
    lifehack: "Zwolnij tempo mowy o 50% i obniż ton głosu podczas kłótni. Spokojny, wolny głos wymusza fizjologiczną koregulację u rozmówcy.",
    group: 'environmental'
  }
];

export const MIKRO_LINKS: DomainLink[] = [
  {
    id: 'm1-m2-override',
    from: 'm1',
    to: 'm2',
    type: 'override',
    direction: 'to',
    label: 'Świadomy Wybór Woli',
    description: 'To moment, w którym zatrzymujesz automatyzm i mówisz sobie: zaraz, nie muszę reagować odruchowo, sam wybiorę, co teraz zrobię.',
    psychology: 'Przejście z automatycznego reagowania na bodźce do celowego kierowania samokontrolą.',
    philosophy: 'Epiktet i pojęcie prohairesis – wewnętrzna przestrzeń wyboru leżąca między bodźcem a reakcją.',
    science: 'Aktywacja kory grzbietowo-bocznej (dlPFC) wyciszająca odruchy podkorowe.',
    lifehack: 'Przed reakcją policz w duchu do 3 i poczuj, że to Ty naciskasz przycisk akcji.'
  },
  {
    id: 'm1-m3-awareness',
    from: 'm1',
    to: 'm3',
    type: 'awareness',
    direction: 'to',
    label: 'Obserwacja Myśli',
    description: 'Patrzysz na swoje myśli jak na liście płynące rzeką – widzisz je, ale nie wskakujesz do wody.',
    psychology: 'Defuzja poznawcza (ACT). Rozdzielenie tożsamości od przepływających myśli.',
    philosophy: 'Fenomenologia Husserla – przyglądanie się zjawiskom w umyśle bez wydawania sądu.',
    science: 'Wyciszenie SIeci Wzbudzeń Podstawowych (DMN) na rzecz kory przedczołowej.',
    lifehack: 'Mów w duchu: Zauważam myśl, że... zamiast: Ja jestem...'
  },
  {
    id: 'm1-m4-awareness',
    from: 'm1',
    to: 'm4',
    type: 'awareness',
    direction: 'to',
    label: 'Obserwacja Afektu',
    description: 'Pozwalasz emocji być w ciele jak pogodzie za oknem – nie próbujesz jej zatrzymać, czekasz aż przejdzie.',
    psychology: 'Uważność emocjonalna i Radykalna Akceptacja (DBT).',
    philosophy: 'Spinoza – poznanie afektu bez oskarżania siebie o jego obecność.',
    science: 'Aktywacja kory przedczołowej redukuje reaktywność współczulną i umożliwia gaśnięcie afektu.',
    lifehack: 'Wizualizuj emocję jako falę – pozwól jej wzrosnąć i opadnąć bez oporu.'
  },
  {
    id: 'm1-m5-awareness',
    from: 'm1',
    to: 'm5',
    type: 'awareness',
    direction: 'to',
    label: 'Zauważenie Pragnienia',
    description: 'Patrzysz na nagłą ochotę sięgnięcia po telefon jak na falę na oceanie – wiesz, że sama opadnie.',
    psychology: 'Technika Urge Surfing z terapii uzależnień.',
    philosophy: 'Stoicka wstrzemięźliwość – obserwacja żądzy bez ulegania jej dyktatowi.',
    science: 'Przerwanie automatycznego sygnału z jądra półleżącego do obwodów ruchowych.',
    lifehack: 'Nastaw stoper na 3 minuty i obserwuj impuls – w większości przypadków sama opadnie.'
  },
  {
    id: 'm1-m6-awareness',
    from: 'm1',
    to: 'm6',
    type: 'awareness',
    direction: 'to',
    label: 'Uważność w Działaniu',
    description: 'Gdy zmywasz naczynia, po prostu zmywasz naczynia – jesteś w 100% obecny w tym, co robią Twoje dłonie.',
    psychology: 'Mindful Action – pełna obecność w prostej czynności fizycznej.',
    philosophy: 'Praktyka Zen – siekanie drewna i noszenie wody jako pełnia bycia.',
    science: 'Zwiększenie spójności sieci czuciowo-ruchowej z korą przedczołową.',
    lifehack: 'Skup się na dotyku i temperaturze wody podczas mycia rąk.'
  },
  {
    id: 'm1-m7-awareness',
    from: 'm1',
    to: 'm7',
    type: 'awareness',
    direction: 'to',
    label: 'Skanowanie Ciała',
    description: 'Sprawdzasz stan swojego ciała tak, jak kierowca sprawdza wskaźniki na desce rozdzielczej samochodu.',
    psychology: 'Body Scan – podstawa redukcji stresu opartej na uważności (MBSR).',
    philosophy: 'Merleau-Ponty – zamieszkiwanie własnego ciała.',
    science: 'Stymulacja kory wyspy (insula) przetwarzającej sygnały z wnętrza organizmu.',
    lifehack: 'Zamknij oczy i przeskanuj uwagę od czubka głowy do stóp.'
  },
  {
    id: 'm2-m1-flow',
    from: 'm2',
    to: 'm1',
    type: 'flow',
    direction: 'to',
    label: 'Odzyskanie Przytomności',
    description: 'Decydujesz się przestać pędzić i wziąć głęboki oddech, by rozejrzeć się, gdzie w ogóle jesteś.',
    psychology: 'Wyjście z automatycznego pilota na rzecz świadomej metakognicji.',
    philosophy: 'Husserlowskie epoche – zawieszenie biegu spraw na rzecz refleksji.',
    science: 'Przełączenie aktywacji z obwodów domyślnych na sieć kontroli wykonawczej.',
    lifehack: 'Ustaw cichy sygnał raz na 2 godziny z pytaniem: Co teraz robię i dlaczego?'
  },
  {
    id: 'm2-m3-override',
    from: 'm2',
    to: 'm3',
    type: 'override',
    direction: 'to',
    label: 'Przekierowanie Skupienia',
    description: 'Zamiast rozmyślać o przykrości sprzed tygodnia, zmuszasz umysł do skupienia się na pracy.',
    psychology: 'Kontrola uwagi w funkcjach wykonawczych.',
    philosophy: 'William James – cechą genialnej woli jest zdolność powracania uwagą do celu.',
    science: 'Grzbietowa kora przedczołowa wycisza niepotrzebne pętle myślowe.',
    lifehack: 'Gdy uciekasz myślami, wypowiedz głośno jedno słowo-klucz związane z zadaniem.'
  },
  {
    id: 'm2-m5-override',
    from: 'm2',
    to: 'm5',
    type: 'override',
    direction: 'to',
    label: 'Blokada Impulsu (PFC)',
    description: 'Widzisz ciastko, masz wielką ochotę je zjeść, ale zabraniasz sobie wyciągnięcia po nie ręki.',
    psychology: 'Hamowanie reakcji (Response Inhibition) – powstrzymanie odruchu.',
    philosophy: 'Stoicki imperatyw samokontroli nad ślepym pożądaniem.',
    science: 'Brzuszno-boczna kora przedczołowa (vlPFC) wysyła sygnał wyciszający prążkowie.',
    lifehack: 'Schowaj dłonie do kieszeni i odczekaj 5 sekund.'
  },
  {
    id: 'm2-m6-override',
    from: 'm2',
    to: 'm6',
    type: 'override',
    direction: 'to',
    label: 'Inicjacja Czynu',
    description: 'Nie masz ochoty wstać z łóżka, ale zrzucasz kołdrę i stawiasz stopy na podłodze.',
    psychology: 'Przełamywanie oporu inicjacji działania (aktywacja behawioralna).',
    philosophy: 'Zasadniczy akt woli u Bergsona.',
    science: 'Projekcje z dlPFC do dodatkowej kory ruchowej (SMA) uruchamiające ruch.',
    lifehack: 'Odlicz 5-4-3-2-1 i wykonaj ruch bez dyskusji z umysłem.'
  },
  {
    id: 'm2-m7-override',
    from: 'm2',
    to: 'm7',
    type: 'override',
    direction: 'to',
    label: 'Kontrola Oddechu',
    description: 'Czujesz stres, więc celowo zwalniasz oddech i rozluźniasz ramiona, by zmusić ciało do spokoju.',
    psychology: 'Celowa regulacja somatyczna top-down.',
    philosophy: 'Panowanie nad machiną ciała u Kartezjusza.',
    science: 'Świadoma praca przepony aktywuje włókna nerwu błędnego obniżające tętno.',
    lifehack: 'Zrób 3 oddechy: 4 sekundy wdech, 7 zatrzymanie, 8 wydech.'
  },
  {
    id: 'm2-m11-flow',
    from: 'm2',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Zużycie Paliwa Decyzyjnego',
    description: 'Im więcej trudnych decyzji podejmujesz w ciągu dnia, tym bardziej czujesz się wykończony wieczorem.',
    psychology: 'Teoria wyczerpywania się zasobów woli (Ego Depletion).',
    philosophy: 'Ekonomia sił duchowych u Nietzschego.',
    science: 'Spadek glukozy i gromadzenie się adenozyny w korze czołowej.',
    lifehack: 'Zmniejsz liczbę decyzji rano – przygotuj ubrania dzień wcześniej.'
  },
  {
    id: 'm3-m1-conflict',
    from: 'm3',
    to: 'm1',
    type: 'conflict',
    direction: 'to',
    label: 'Fuzja Poznawcza',
    description: 'Przerażająca myśl tak bardzo Cię straszy, że zapominasz, że to tylko myśl i traktujesz ją jak fakt.',
    psychology: 'Fuzja poznawcza (Cognitive Fusion) w terapii ACT.',
    philosophy: 'Zagubienie w świecie wyobrażeń (Spinoza).',
    science: 'Nadaktywność DMN przysłaniająca korę obwodową.',
    lifehack: 'Wyobraź sobie straszną myśl napisaną śmieszną czcionką.'
  },
  {
    id: 'm3-m4-flow',
    from: 'm3',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Pętla CBT (Myśl -> Uczucie)',
    description: 'Gdy pomyślisz szef mnie wywali, natychmiast czujesz ścisk w żołądku i strach.',
    psychology: 'Model A-B-C Becka w Terapii Poznawczo-Behawioralnej.',
    philosophy: 'Epiktet – zdarzenia nie mają wartości, dopóki umysł nie nada im sądu.',
    science: 'Sygnały glutaminergiczne z kory czołowej stymulujące ciało migdałowate.',
    lifehack: 'Sprawdź fakt: Czy mam dowody na tę myśl, czy to spekulacja?'
  },
  {
    id: 'm3-m6-flow',
    from: 'm3',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Realizacja Intencji',
    description: 'Przypominasz sobie muszę kupić chleb i skręcasz autem do sklepu.',
    psychology: 'Przekład planu poznawczego na skrypt wykonawczy.',
    philosophy: 'Kantowska koncepcja rozumu praktycznego.',
    science: 'Przekazywanie instrukcji z dlPFC do kory przedruchowej.',
    lifehack: 'Zapisz plan w formule krok-po-kroku na kartce.'
  },
  {
    id: 'm3-m7-flow',
    from: 'm3',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Psychosomatyka Stresu',
    description: 'Zamartwianie się sprawami sprawia, że po dwóch godzinach boli Cię kark i głowa.',
    psychology: 'Reakcja psychosomatyczna na przewlekłe ruminacje.',
    philosophy: 'Kartezjańska spójność substancji myślanej i rozciągłej.',
    science: 'Przewlekła aktywacja osi HPA wyrzuca kortyzol i obkurcza naczynia.',
    lifehack: 'Gdy zauważysz ruminacje, zrób 10 przysiadów.'
  },
  {
    id: 'm3-m8-flow',
    from: 'm3',
    to: 'm8',
    type: 'flow',
    direction: 'to',
    label: 'Krystalizacja Schematu',
    description: 'Powtarzanie sobie nigdy mi się nie uda sprawia, że po miesiącu zaczynasz w to głęboko wierzyć.',
    psychology: 'Utrwalanie ruminacji i wyuczona beznadziejność (Seligman).',
    philosophy: 'Nawyk myślowy jako druga natura (Arystoteles).',
    science: 'Długotrwałe wzmocnienie synaptyczne (LTP).',
    lifehack: 'Przerywaj ruminacje w zarodku – nie pozwalaj myśli krążyć dłużej niż minutę.'
  },
  {
    id: 'm4-m1-conflict',
    from: 'm4',
    to: 'm1',
    type: 'conflict',
    direction: 'to',
    label: 'Zalew Afektywny',
    description: 'Przytłaczająca fala gniewu lub lęku zdmuchuje perspektywę obserwatora.',
    psychology: 'Porwanie emocjonalne (Amygdala Hijack).',
    philosophy: 'Niewola namiętności u Spinozy.',
    science: 'Gwałtowny skok aktywności ciała migdałowatego odłączający PFC.',
    lifehack: 'Dotknij zimnej powierzchni lub przemyj twarz zimną wodą.'
  },
  {
    id: 'm4-m3-flow',
    from: 'm4',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Uzasadnienie Emocjonalne',
    description: 'Odczuwany lęk sprawia, że umysł dorabia katastroficzne scenariusze, by go wyjaśnić.',
    psychology: 'Błąd poznawczy emotional reasoning.',
    philosophy: 'Hume – rozum jest niewolnikiem namiętności.',
    science: 'Układ limbiczny wymusza spójność afektywną w korze czołowej.',
    lifehack: 'Powiedz: Czuję lęk, ale to nie oznacza, że istnieje zagrożenie.'
  },
  {
    id: 'm4-m5-flow',
    from: 'm4',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Zasilanie Impulsu',
    description: 'Intensywna złość błyskawicznie zamienia się w impuls do ataku lub uderzenia w stoł.',
    psychology: 'Wyzwolenie odruchu behawioralnego przez afekt.',
    philosophy: 'Spinozjański conatus napędzany afektem.',
    science: 'Układ limbiczny wyzwalający pobudzenie ruchowe w pniu mózgu.',
    lifehack: 'Działanie przeciwne z DBT – zrób celowo miękki krok wycofania.'
  },
  {
    id: 'm4-m6-flow',
    from: 'm4',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Motywacja Afektywna',
    description: 'Emocje przygotowują ciało do przytulenia kogoś lub ucieczki z miejsca zagrożenia.',
    psychology: 'Terapia EFT – emocje jako wektory motywacyjne.',
    philosophy: 'Afekt jako źródło wektora życiowego.',
    science: 'Aktywacja autonomicznego układu nerwowego do działania.',
    lifehack: 'Zauważ, do jakiego czynu popycha Cię dana emocja.'
  },
  {
    id: 'm4-m7-flow',
    from: 'm4',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Somatyzacja Afektu',
    description: 'Smutek staje się ciężarem w klatce piersiowej, a lęk ściśniętym żołądkiem.',
    psychology: 'Terapia Somatic Experiencing (Peter Levine).',
    philosophy: 'Merleau-Ponty – przeżywające ciało.',
    science: 'Wyrzut kortyzolu i zmiana tonusu naczyniowego.',
    lifehack: 'Skieruj łagodną uwagę w punkt somatycznego napięcia.'
  },
  {
    id: 'm4-m10-conflict',
    from: 'm4',
    to: 'm10',
    type: 'conflict',
    direction: 'to',
    label: 'Aleksytymia (Paraliż Mowy)',
    description: 'Przytłaczająca emocja sprawia, że brakuje Ci słów, by opisać co czujesz.',
    psychology: 'Aleksytymia traumatyczna – brak słów dla afektu.',
    philosophy: 'Levinas – to co niewyrażalne w uderzeniu cierpienia.',
    science: 'Odłączenie funkcjonalne ciała migdałowatego od pola Broca.',
    lifehack: 'Opisz emocję kolorem lub metaforą, gdy brakuje słów.'
  },
  {
    id: 'm5-m2-conflict',
    from: 'm5',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Przełamanie Woli (Pokusa)',
    description: 'Potężny skok ochoty wyłącza rozsądek i zmusza wolę do uległości.',
    psychology: 'Porażka samokontroli pod wpływem dopaminy.',
    philosophy: 'Schopenhauer – ślepy pęd wygrywający z intelektem.',
    science: 'Wyrzut dopaminy w jadrze półleżącym wyłącza kontrolę PFC.',
    lifehack: 'Zmień otoczenie – nie walcz z impulsem w jego zasięgu.'
  },
  {
    id: 'm5-m6-flow',
    from: 'm5',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Działanie Impulsywne',
    description: 'Sęgasz po telefon bez myślenia natychmiast, gdy poczujesz sekundę nudy.',
    psychology: 'Odruch automatyczny pominięty przez refleksję.',
    philosophy: 'Bezwolna determinacja fizyczna.',
    science: 'Bezpośredni szlak prążkowie-kora ruchowa.',
    lifehack: 'Stwórz tarcie – połóż telefon w drugim pokoju.'
  },
  {
    id: 'm6-m3-flow',
    from: 'm6',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Informacja Zwrotna z Działania',
    description: 'Zrobienie pierwszego kroku daje twardy dowód, który zmienia Twoje myślenie.',
    psychology: 'Eksperymenty behawioralne w CBT.',
    philosophy: 'Pragmatyzm Peirce a – prawda testowana w działaniu.',
    science: 'Kodowanie błędu predykcji dopaminergicznej po akcji.',
    lifehack: 'Traktuj działanie jako zbieranie danych, nie jako sprawdzian.'
  },
  {
    id: 'm6-m4-flow',
    from: 'm6',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Sprzężenie Zwrotne Ciała',
    description: 'Uśmiech i wyprostowana postawa po kilku chwilach poprawiają odczuwany nastrój.',
    psychology: 'Hipoteza sprzężenia zwrotnego postawy (Power Posing).',
    philosophy: 'William James – jest nam smutno, bo płaczemy.',
    science: 'Receptory mięśniowe wysyłające sygnał bezpieczeństwa do kory wyspy.',
    lifehack: 'Wyprostuj plecy i otwórz dłonie na 60 sekund.'
  },
  {
    id: 'm7-m4-flow',
    from: 'm7',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Interocepcja (Ciało -> Afekt)',
    description: 'Ściśnięty żołądek z powodu głodu zostaje zinterpretowany przez mózg jako lęk.',
    psychology: 'Teoria konstruowanych emocji (Barrett).',
    philosophy: 'Nietzsche – ciało jako wielki rozum.',
    science: 'Kora wyspy budująca afekt z sygnałów narządowych.',
    lifehack: 'Gdy czujesz niepokój, sprawdź najpierw czy nie jesteś po prostu głodny.'
  },
  {
    id: 'm8-m3-flow',
    from: 'm8',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Filtr Poznawczy (Schemat)',
    description: 'Głębokie przekonanie, że ludzie są wrodzy, sprawia że zwykły uśmiech uznajesz za kpinę.',
    psychology: 'Terapia Schematu (Young) i zniekształcenia poznawcze.',
    philosophy: 'Kantowskie kategorie rozumu filtrujące rzeczywistość.',
    science: 'Sztywne ścieżki synaptyczne faworyzujące znane interpretacje.',
    lifehack: 'Zapytaj: Z jakiej ukrytej reguły wyrosła ta myśl?'
  },
  {
    id: 'm9-m1-conflict',
    from: 'm9',
    to: 'm1',
    type: 'conflict',
    direction: 'to',
    label: 'Zawłaszczenie Uwagi',
    description: 'Głośny hałas lub powiadomienie bezczelnie wyrywają Cię z głębokiego skupienia.',
    psychology: 'Dystrakcja środowiskowa i skrajne przebodźcowanie.',
    philosophy: 'Presja fizyczna otoczenia.',
    science: 'Odruch orientacyjny wyzwalany przez jądra pnia mózgu.',
    lifehack: 'Włącz tryb nie przeszkadzać na czas głębokiej pracy.'
  },
  {
    id: 'm9-m6-flow',
    from: 'm9',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Afordancje Przestrzenne',
    description: 'Książka leżąca na poduszce zachęca do czytania, a telefon na biurku do rozpraszania.',
    psychology: 'Architektura wyboru w psychologii środowiskowej.',
    philosophy: 'Determinizm materialny otoczenia.',
    science: 'Bodźce wzrokowe aktywujące reprezentacje motoryczne.',
    lifehack: 'Ułatwiaj dobre zachowania i stawiaj przeszkody złym.'
  },
  {
    id: 'm10-m4-override',
    from: 'm10',
    to: 'm4',
    type: 'override',
    direction: 'to',
    label: 'Nazywanie Afektu (Affect Labeling)',
    description: 'Nazwanie emocji precyzyjnym słowem natychmiast obniża jej natężenie.',
    psychology: 'Affect Labeling w terapii poznawczej i ACT.',
    philosophy: 'Wittgenstein – granice języka granicami świata.',
    science: 'Pole Broca wyciszające ciało migdałowate.',
    lifehack: 'Zamiast jest źle powiedz: czuję rozczarowanie.'
  },
  {
    id: 'm11-m2-flow',
    from: 'm11',
    to: 'm2',
    type: 'flow',
    direction: 'to',
    label: 'Zasilanie Funkcji Wykonawczych',
    description: 'Sen i jedzenie dają kora czołowej siłę niezbędną do trzymania nerwów na wodzy.',
    psychology: 'Budżetowanie metaboliczne samokontroli.',
    philosophy: 'Materializm biologiczny.',
    science: 'Dopływ glukozy niezbędny dla pracy vlPFC.',
    lifehack: 'Nie podejmuj kluczowych ustaleń na zmęczeniu (HALT).'
  },
  {
    id: 'm11-m4-flow',
    from: 'm11',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Modulacja Biochemiczna',
    description: 'Poziom hormonów, glukozy i neuroprzekaźników dyktuje bazowy poziom nerwowości lub spokoju w danym dniu.',
    psychology: 'Biologiczne i metaboliczne podłoże zmienności nastroju i afektu.',
    philosophy: 'Redukcjonizm biologiczny.',
    science: 'Stężenie kortyzolu, dopaminy i glukozy stymulujące ciało migdałowate i korę czołową.',
    lifehack: 'Zrób pakiet badań krwi przy przewlekłym spadku nastroju lub energii.'
  },
  {
    id: 'm13-m7-flow',
    from: 'm13',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Koregulacja Somatyczna',
    description: 'Obecność spokojnej osoby wycisza kołatanie serca i układ nerwowy.',
    psychology: 'Teoria poliwagalna Stephena Porgesa.',
    philosophy: 'Relacja Ja-Ty u Martina Bubera.',
    science: 'Gałąź brzuszna nerwu błędnego obniżająca tętno.',
    lifehack: 'Szukaj spokojnego kontaktu wzrokowego w strefie stresu.'
  },
  {
    id: 'm9-m11-flow',
    from: 'm9',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Bio-rytm i Otoczenie',
    description: 'Gdy za oknem jest ciemno i ponuro przez całe tygodnie, Twoje ciało nie pyta o zdanie – produkuje mniej serotoniny i więcej melatoniny, a Ty czujesz, że po prostu brakuje Ci prądu.',
    psychology: 'Psychologia środowiskowa opisuje to jako sezonowe zaburzenie afektu (SAD) – stan, w którym środowisko fizyczne bezpośrednio obniża napęd życiowy.',
    philosophy: 'Determinizm materialny: organizm jest częścią przyrody i ulega jej cyklom, zanim kora mózgowa cokolwiek zdoła zaplanować.',
    science: 'Fotoperiod (ilość światła) dociera przez siatkówkę do jądra skrzyżowanego (SCN) i steruje syntezą melatoniny oraz kortyzolu w nadnerczach.',
    lifehack: 'Rano po przebudzeniu zapal jasne światło lub wyjdź na 10 minut na zewnątrz, żeby dać mózgowi sygnał do wyłączenia melatoniny.'
  },
  {
    id: 'm9-m7-flow',
    from: 'm9',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Nacisk i Temperatura Otoczenia',
    description: 'Ciasny kołnierzyk, szorstka metka w koszulce albo lodowaty wiatr natychmiast zmieniają to, co czujesz w ciele, zanim w ogóle pomyślisz, że coś jest nie tak.',
    psychology: 'Przeciążenie sensoryczne – powtarzalne, nieprzyjemne bodźce dotykowe podprogowo drenują zasoby uwagi i podnoszą napięcie mięśniowe.',
    philosophy: 'Fenomenologia Merleau-Ponty ego: ciało jest pierwszą powierzchnią styku ze światem zewnętrznym i odbiera go bezpośrednio.',
    science: 'Pobudzenie obwodowych receptorów czuciowych (mechanoreceptorów i termoreceptorów) wysyła sygnały do rdzenia kręgowego i kory czuciowej (S1).',
    lifehack: 'Usunięcie jednego irytującego bodźca fizycznego (np. zmiana ciasnego ubrania czy wyciszenie hałasu) błyskawicznie obniża bazowy poziom spięcia.'
  },
  {
    id: 'm9-m5-flow',
    from: 'm9',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Wyzwalacz Środowiskowy (Afordancja)',
    description: 'Zobaczenie chipsów leżących na wierzchu albo powiadomienia na ekranie wywołuje błyskawiczną ochotę sięgnięcia po nie, chociaż sekundę wcześniej wcale o tym nie myślałeś.',
    psychology: 'Teoria afordancji Gibsona i reaktywność na bodźce (Cue-Reactivity) – widok okazji wyzwala odruch chęci bez udziału rozsądku.',
    philosophy: 'Mądrość ludowa okazja czyni złodzieja – środowisko stawia przed człowiekiem pokusę, która sama ciągnie za sznurki zachowania.',
    science: 'Gwałtowny wyrzut dopaminy w jądrze półleżącym wywołany bodźcem wzrokowym generuje sygnał nagrody jeszcze przed reakcją kory czołowej.',
    lifehack: 'Nie walcz z silną wolą – schowaj wyzwalacz z oczu. Gdy znika bodziec wzrokowy, impuls opada o 80%.'
  },
  {
    id: 'm11-m7-flow',
    from: 'm11',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Falowanie Biochemiczne w Ciele',
    description: 'Spadek cukru albo trzecia kawa z rzędu daje natychmiastowe roztrzęsienie, drżenie rąk i ciężkość w żołądku, zanim zdążysz pomyśleć, że coś jest nie tak.',
    psychology: 'Interocepcja, czyli zdolność mózgu do odczytywania chemicznych wskaźników organizmu i przekładania ich na surowe odczucia cielesne.',
    philosophy: 'Monizm cielesno-duchowy: metabolizm i wrażenia z ciała to ten sam proces widziany z zewnątrz i od wewnątrz.',
    science: 'Kora wyspy (insula) odbiera sygnały o poziomie glukozy, mleczanu i pH krwi i buduje z nich mapę odczuć somatycznych.',
    lifehack: 'Gdy czujesz dziwne roztrzęsienie w ciele, zanim uznasz to za lęk psychiczny, zjedz coś wartościowego lub wypij szklankę wody.'
  },
  {
    id: 'm7-m11-flow',
    from: 'm7',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Sygnał Metaboliczny z Ciała',
    description: 'Intensywny wysiłek fizyczny, gorączka albo skurcz mięśni natychmiast zmieniają skład krwi, tętno i poziomy hormonów. Ciało nie czeka na pozwolenie kory mózgowej.',
    psychology: 'Sprzężenie zwrotne somatyczno-endokrynne. Aktywność fizyczna zmienia biochemię szybciej niż jakakolwiek interwencja psychologiczna.',
    philosophy: 'Ciało jako samodzielny sprawca zmian wewnętrznych, a nie bierna maszyna czekająca na rozkazy umysłu.',
    science: 'Wysiłek fizyczny powoduje wyrzut endorfin, BDNF i adrenaliny, jednocześnie obniżając poziom kortyzolu w ciągu 20-30 minut.',
    lifehack: 'Gdy czujesz się fatalnie i żadna myśl nie pomaga, zrób 20 przysiadów. Wymuszona zmiana biochemii działa szybciej niż racjonalizowanie.'
  },
  {
    id: 'm11-m5-flow',
    from: 'm11',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Spadek Hamowania przy Wyczyszczonej Baterii',
    description: 'Kiedy jesteś niewyspany albo bardzo głodny, masz dziesięć razy mniej cierpliwości i ulegasz impulsom zjedzenia śmieciowego jedzenia lub wybuchnięcia gniewem.',
    psychology: 'Teoria ego depletion i brak zasobów metabolicznych do samokontroli.',
    philosophy: 'Nietzscheańska krytyka czystej woli: tak zwana słabość charakteru to często po prostu wyczerpanie biologiczne.',
    science: 'Spadek glukozy w korze grzbietowo-bocznej (dlPFC) uniemożliwia wysyłanie hamujących sygnałów GABA-ergicznych do obwodów nagrody.',
    lifehack: 'Gdy czujesz nagły, agresywny impuls ulegania nawykowi, sprawdź najpierw czy nie działa reguła HALT (Głód, Złość, Samotność, Zmęczenie).'
  },
  {
    id: 'm11-m3-flow',
    from: 'm11',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Mgła Mózgowa',
    description: 'Stan zapalny w ciele albo zjazd po stymulantach wywołuje czarne myśli i mgłę mózgową. Nie dlatego, że masz problemy psychiczne, ale dlatego że mózg dosłownie nie ma paliwa.',
    psychology: 'Biologiczna podstawa ruminacji. Osłabiona elastyczność poznawcza pod wpływem obciążenia metabolicznego nie pozwala umysłowi przeskakiwać między perspektywami.',
    philosophy: 'Spinozjańska równoległość: porządek i połączenie myśli jest tym samym, co porządek i połączenie stanów ciała.',
    science: 'Proinflamacyjne cytokiny aktywują mikroglej w mózgu i zmieniają metabolizm tryptofanu, wywołując czarne scenariusze myślowe.',
    lifehack: 'Nie próbuj przegadać racjonalnie mgły mózgowej przy wyczerpaniu. Zrób przerwę na sen lub lekki ruch, by zresetować biochemię.'
  },
  {
    id: 'm3-m11-flow',
    from: 'm3',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Stresogeneza Biochemiczna',
    description: 'Zamartwianie się w głowie natychmiast zalewa krew kortyzolem. Wystarczą dwie godziny ruminacji, żebyś czuł się, jakbyś przebiegł maraton.',
    psychology: 'Ruminacja jako generator stresu biochemicznego. Obsesyjne przeżuwanie myśli uruchamia reakcję stresową identyczną z fizycznym zagrożeniem.',
    philosophy: 'Kartezjańska spójność substancji myślanej i rozciągłej: myśl potrafi zmienić chemię ciała równie skutecznie jak trucizna.',
    science: 'Przewlekła aktywacja osi HPA przez ruminacje powoduje wyrzut kortyzolu, wzrost cytokin zapalnych i obkurczenie naczyń krwionośnych.',
    lifehack: 'Gdy przyłapiesz się na godzinnym zamartwianiu, wstań i zrób cokolwiek fizycznego. Mózg nie potrafi jednocześnie ruminować i koordynować ruch.'
  },
  {
    id: 'm13-m5-flow',
    from: 'm13',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Wzbudzenie w Obecności Innych',
    description: 'Bliskość atrakcyjnej osoby albo przebywanie w nakręconym emocjonalnie tłumie natychmiast wyzwala automatyczne odruchy: chęć zbliżenia, rywalizacji albo ucieczki.',
    psychology: 'Impulsywność relacyjna i reakcje przywiązaniowe wyzwalane bodźcami społecznymi.',
    philosophy: 'Koncepcja mimetycznego pożądania René Girarda: nasze impulsy i pragnienia często rodzą się z podglądania innych ludzi.',
    science: 'Pobudzenie podwzgórza i układu limbicznego pod wpływem sygnałów niewerbalnych (wzrok, odległość fizyczna, zapach).',
    lifehack: 'W sytuacjach intensywnego napięcia społecznego zrób fizyczny krok w tył, by przerwać automatyczny odruch.'
  },
  {
    id: 'm13-m4-flow',
    from: 'm13',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Zarażenie Emocjonalne',
    description: 'Wchodzisz do pokoju, w którym ktoś jest wściekły albo przerażony, i natychmiast czujesz ciężar w żołądku. Nie musisz wiedzieć, o co chodzi. Ciało rozmówcy już Ci powiedziało.',
    psychology: 'Zjawisko zarażania emocjonalnego (Emotional Contagion). Układ nerwowy automatycznie kopiuje stan afektywny osoby w pobliżu.',
    philosophy: 'Relacja Ja-Ty Martina Bubera: autentyczne spotkanie z drugim człowiekiem zmienia bezpośrednio nasz wewnętrzny stan czucia.',
    science: 'Neurony lustrzane i gałąź brzuszna nerwu błędnego odczytują mikroekspresje twarzy i napięcia mięśniowe u rozmówcy w ułamkach sekundy.',
    lifehack: 'Zanim wejdziesz na spotkanie z kimś zdenerwowanym, zrób trzy głębokie oddechy. Wchodzisz z niższym tonem bazowym i trudniej Cię zarazić.'
  },
  {
    id: 'm4-m13-flow',
    from: 'm4',
    to: 'm13',
    type: 'flow',
    direction: 'to',
    label: 'Emisja Afektu w Relacji',
    description: 'Twój spokój potrafi wyciszyć kogoś w panice. I odwrotnie, Twoja niekontrolowana złość rozprzestrzenia się na wszystkich w pokoju jak pożar.',
    psychology: 'Koregulacja emocjonalna: zdolność jednej osoby do stabilizowania lub destabilizowania układu nerwowego drugiej przez sam stan własnego ciała.',
    philosophy: 'Levinasowski Inny: moja emocja nie kończy się na mojej skórze, lecz przenika w przestrzeń spotkania i zmienia drugiego człowieka.',
    science: 'Aktywacja gałęzi brzusznej nerwu błędnego u nadawcy moduluje ton głosu i mimikę, wymuszając fizjologiczną synchronizację u odbiorcy.',
    lifehack: 'Podczas trudnej rozmowy świadomie obniż ton głosu i zwolnij oddech. Zmusisz układ nerwowy drugiej osoby do koregulacji w dół.'
  },
  {
    id: 'm10-m3-flow',
    from: 'm10',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Klocki Językowe Myśli',
    description: 'Nie jesteś w stanie pomyśleć skomplikowanej analizy, jeśli nie znasz odpowiednich słów. Język podsuwa klocki, z których układasz swoje wewnętrzne narracje.',
    psychology: 'Koncepcja mowy wewnętrznej Lwa Wygotskiego. Myślenie to po prostu cichy dialog z samym sobą, ograniczony dostępnym słownictwem.',
    philosophy: 'Wittgenstein: Granice mojego języka oznaczają granice mojego świata. Słowa budują geometrię myśli.',
    science: 'Sieci językowe (ośrodek Broca i Wernickego) ściśle współpracują z korą przedczołową przy generowaniu i porządkowaniu myśli.',
    lifehack: 'Poszerzaj słownictwo opisujące zjawiska wokół siebie. Im bardziej precyzyjne słowo wybierzesz, tym mniej chaotyczna będzie myśl.'
  },
  {
    id: 'm3-m10-flow',
    from: 'm3',
    to: 'm10',
    type: 'flow',
    direction: 'to',
    label: 'Myśl Szuka Słowa',
    description: 'Masz mglistą intuicję albo przeczucie, ale nie potrafisz go nikomu wyjaśnić, dopóki nie znajdziesz właściwego zdania. Myśl domaga się ubrania w słowa.',
    psychology: 'Werbalizacja jako narzędzie krystalizacji myśli. Proces nazywania zmusza do precyzji i odsłania luki logiczne.',
    philosophy: 'Hermeneutyka Gadamera: rozumienie dokonuje się w języku, nie poza nim. Myśl, która nie znalazła wyrazu, pozostaje niekompletna.',
    science: 'Aktywacja kory przedczołowej przy przetwarzaniu abstrakcyjnych konceptów automatycznie pobudza sieci językowe w płacie skroniowym.',
    lifehack: 'Gdy czujesz, że coś ważnego kołacze się w głowie, ale nie wiesz co, zacznij pisać na kartce strumień świadomości. Myśl wykrystalizuje się w procesie pisania.'
  },
  {
    id: 'm8-m1-awareness',
    from: 'm8',
    to: 'm1',
    type: 'awareness',
    direction: 'to',
    label: 'Okulary Uwagi Obserwatora',
    description: 'Gdy głęboko wierzysz, że jesteś niezdarą, Obserwator w Tobie natychmiast wyłapuje każdy twój potknięty krok, a całkowicie ignoruje momenty, gdy poradziłeś sobie świetnie.',
    psychology: 'Uwaga selektywna i błąd potwierdzenia (Confirmation Bias): przekonania decydują o tym, na co w ogóle zwracasz uwagę.',
    philosophy: 'Kantyzm fenomenologiczny: nie widzimy rzeczy takimi, jakimi są, ale takimi, jakimi są nasze ramy pojęciowe.',
    science: 'Pętla ze wzgórza do kory wzrokowej i czuciowej, która przesyła do świadomej uwagi tylko sygnały zgodne z wewnętrznym modelem predykcyjnym.',
    lifehack: 'Gdy zauważysz, że stale wyłapujesz z otoczenia tylko negatywy, zapytaj Obserwatora: Na co jeszcze teraz NIE zwracam uwagi? To rozszerza pole świadomości.'
  },
  // === STRONG LINKS (20) ===
  {
    id: 'm2-m4-override',
    from: 'm2',
    to: 'm4',
    type: 'override',
    direction: 'to',
    label: 'Regulacja Emocji Top-Down',
    description: 'Czujesz narastający gniew, ale celowo zwalniasz oddech i mówisz sobie: nie dam się temu porwać. Wola bierze emocje za kołnierz.',
    psychology: 'Regulacja emocji odgórna (Top-Down Emotion Regulation). James Gross wyróżnia strategię ponownej oceny poznawczej jako najzdrowszą formę kontroli afektu.',
    philosophy: 'Stoicka apatia: nie eliminacja uczuć, ale odmowa oddania im sterów. Seneka mówił, że gniew mija, gdy mu każesz poczekać.',
    science: 'Grzbietowo-boczna kora przedczołowa (dlPFC) wysyła sygnały hamujące do ciała migdałowatego, obniżając intensywność reakcji emocjonalnej.',
    lifehack: 'Gdy emocja narasta, nazwij ją na głos jednym słowem (złość, strach, wstyd) i weź trzy wolne oddechy. To mechanicznie uruchamia PFC.'
  },
  {
    id: 'm2-m9-override',
    from: 'm2',
    to: 'm9',
    type: 'override',
    direction: 'to',
    label: 'Architektura Wyboru',
    description: 'Zamiast walczyć z ochotą na chipsy siłą woli, po prostu ich nie kupujesz i nie trzymasz w domu. Zmieniasz otoczenie, żeby nie musieć walczyć.',
    psychology: 'Architektura wyboru (Choice Architecture) Thalera i Sunsteina. Projektowanie środowiska tak, by zdrowe decyzje były ścieżką najmniejszego oporu.',
    philosophy: 'Pragmatyczny determinizm: zamiast zmieniać duszę, zmień warunki, w których dusza operuje.',
    science: 'Redukcja bodźców wyzwalających w otoczeniu zmniejsza aktywację szlaków dopaminergicznych w prążkowiu, bo nie ma czego pożądać.',
    lifehack: 'Wieczorem przygotuj otoczenie na jutro: schowaj rozpraszacze, połóż książkę na poduszce, ustaw budzik w drugim pokoju.'
  },
  {
    id: 'm3-m2-conflict',
    from: 'm3',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Paraliż Analityczny',
    description: 'Analizujesz w głowie tyle scenariuszy, że nie jesteś w stanie podjąć żadnej decyzji. Im więcej myślisz, tym bardziej się blokujesz.',
    psychology: 'Analysis Paralysis i ruminacyjna blokada decyzyjna. Overthinking zwiększa postrzegane ryzyko każdej opcji, aż żadna nie wydaje się bezpieczna.',
    philosophy: 'Paradoks Buridana: osioł między dwoma identycznymi stogami siana umiera z głodu, bo nie potrafi wybrać.',
    science: 'Nadmierna aktywność brzuszno-przyśrodkowej kory przedczołowej (vmPFC) zalewa obwody decyzyjne sprzecznymi sygnałami i paraliżuje dodatkową korę ruchową (SMA).',
    lifehack: 'Daj sobie limit: jeśli w 5 minut nie podejmiesz decyzji, rzuć monetą. Losowa decyzja jest lepsza niż brak decyzji.'
  },
  {
    id: 'm3-m5-flow',
    from: 'm3',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Antycypacja Nagrody',
    description: 'Wystarczy, że pomyślisz o czekoladzie leżącej w szafce, a natychmiast czujesz ochotę, żeby po nią sięgnąć. Myśl o nagrodzie sama generuje pragnienie.',
    psychology: 'Anticipatory desire i Cue-Reactivity w psychologii uzależnień. Mentalne wyobrażenie nagrody uruchamia te same obwody, co sama nagroda.',
    philosophy: 'Epikurejski paradoks: pragnienie przyjemności potrafi być bardziej dokuczliwe niż sam brak przyjemności.',
    science: 'Wyobrażenie nagrody aktywuje brzuszne pole nakrywki (VTA) i powoduje wyrzut dopaminy w jądrze półleżącym, generując silną motywację do działania.',
    lifehack: 'Gdy nachodzi Cię ochota, nie walcz z nią ani nie karm jej wyobraźnią. Skieruj uwagę na zupełnie inny zmysł: posłuchaj muzyki albo wyjdź na zewnątrz.'
  },
  {
    id: 'm4-m2-conflict',
    from: 'm4',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Odwaga lub Paraliż Emocjonalny',
    description: 'Paraliżujący strach przed odmową sprawia, że nie jesteś w stanie nawet podnieść telefonu i zadzwonić. Albo odwrotnie: gniew daje Ci siłę do walki, której normalnie byś nie miał.',
    psychology: 'Dwukierunkowy wpływ emocji na wolę. Lęk może całkowicie zablokować inicjację działania, podczas gdy kontrolowany gniew bywa źródłem energii do przełamania oporu.',
    philosophy: 'Arystotelesowska odwaga: cnota nie polega na braku strachu, lecz na działaniu pomimo niego.',
    science: 'Wysoki poziom kortyzolu w trybie lękowym dezaktywuje korę przedczołową, a umiarkowany poziom noradrenaliny przy kontrolowanym gniewie ją wzmacnia.',
    lifehack: 'Gdy strach Cię paraliżuje, wykonaj najmniejszy możliwy krok. Nie dzwoń jeszcze, tylko znajdź numer. Mikro-akcja łamie inercję strachu.'
  },
  {
    id: 'm8-m2-conflict',
    from: 'm8',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Paraliż lub Mobilizacja Schematyczna',
    description: 'Gdy głęboko wierzysz, że i tak się nie uda, nie jesteś w stanie zmusić się do pierwszego kroku. Ale gdy wierzysz, że potrafisz, wola rośnie trzykrotnie.',
    psychology: 'Poczucie własnej skuteczności (Self-Efficacy) Alberta Bandury. Przekonanie o własnej kompetencji jest silniejszym predyktorem działania niż obiektywne umiejętności.',
    philosophy: 'Nietzscheańska wola mocy: wiara w siebie nie jest iluzją, lecz warunkiem koniecznym każdego czynu twórczego.',
    science: 'Przekonanie o własnej skuteczności koreluje z wyższą aktywnością grzbietowej kory przedczołowej i niższą reaktywnością ciała migdałowatego.',
    lifehack: 'Przypomnij sobie ostatnią trudną rzecz, którą udało Ci się zrobić. Dosłownie zwizualizuj tamten moment sukcesu. To ładuje baterię poczucia skuteczności.'
  },
  {
    id: 'm8-m4-flow',
    from: 'm8',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Generowanie Afektu z Przekonań',
    description: 'Gdybyś głęboko wierzył, że jesteś bezwartościowy, każda drobna krytyka wbijałaby się jak nóż. To nie krytyka boli. Boli przekonanie, które ją wyolbrzymia.',
    psychology: 'Model A-B-C Aarona Becka: nie zdarzenia (A) wywołują emocje (C), ale nasze przekonania o nich (B). To rdzeń całej terapii poznawczej.',
    philosophy: 'Epiktet: Nie niepokoją nas rzeczy, lecz mniemania, jakie mamy o rzeczach.',
    science: 'Utrwalone schematy poznawcze w korze czołowej obniżają próg aktywacji ciała migdałowatego, czyniąc osobę nadmiernie wrażliwą na zgodne bodźce.',
    lifehack: 'Gdy emocja jest nieproporcjonalnie silna do sytuacji, zapytaj: jakie przekonanie musiałoby być prawdą, żebym czuł to tak mocno?'
  },
  {
    id: 'm8-m6-flow',
    from: 'm8',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Samospełniające się Proroctwo',
    description: 'Kto wierzy, że nie da rady, nawet nie próbuje. Kto wierzy, że potrafi, próbuje i zbiera dowody na swoją skuteczność. Przekonanie buduje lub niszczy działanie.',
    psychology: 'Samospełniająca się przepowiednia (Self-Fulfilling Prophecy) Roberta Mertona i wyuczona bezradność (Learned Helplessness) Martina Seligmana.',
    philosophy: 'Pragmatyzm Williama Jamesa: wiara w sukces jest jednym z warunków osiągnięcia sukcesu.',
    science: 'Niskie poczucie skuteczności obniża aktywność kory przedruchowej (pre-SMA), co fizycznie utrudnia inicjację ruchu.',
    lifehack: 'Zacznij od zadania tak małego, że nie jesteś w stanie nie wierzyć, że Ci się uda. Zbuduj serię drobnych sukcesów.'
  },
  {
    id: 'm4-m8-flow',
    from: 'm4',
    to: 'm8',
    type: 'flow',
    direction: 'to',
    label: 'Gorąca Zmiana Przekonań',
    description: 'W stanie euforii wierzysz, że wszystko jest możliwe. W stanie rozpaczy wierzysz, że nic się nie uda. Emocja zmienia to, w co wierzysz, z minuty na minutę.',
    psychology: 'Hot Cognition: przetwarzanie poznawcze zależne od stanu emocjonalnego. Pod wpływem silnych emocji mózg przepisuje przekonania na ich obraz.',
    philosophy: 'Pascalowska logika serca: serce ma swoje racje, których rozum nie zna. Emocje ustanawiają prawdy, które intelekt potem tylko dekoruje.',
    science: 'Pobudzenie ciała migdałowatego moduluje konsolidację pamięci w hipokampie, wzmacniając wspomnienia zgodne z aktualnym stanem emocjonalnym.',
    lifehack: 'Nie podejmuj trwałych decyzji życiowych w stanie silnej emocji. Zapisz decyzję, przeczekaj 24 godziny i przeczytaj ją na zimno.'
  },
  {
    id: 'm10-m8-override',
    from: 'm10',
    to: 'm8',
    type: 'override',
    direction: 'to',
    label: 'Reframing Językowy',
    description: 'Zamiana słów "jestem ofiarą" na "to była trudna sytuacja, z którą sobie poradziłem" zmienia nie tylko słowa, ale całe przekonanie o sobie.',
    psychology: 'Reframing poznawczy w terapii narracyjnej i NLP. Zmiana opowieści o sobie zmienia schemat, przez który filtrujesz rzeczywistość.',
    philosophy: 'Hermeneutyka Ricoeura: tożsamość jest narracją, a nie faktem. Kto zmienia swoją historię, zmienia siebie.',
    science: 'Nowe wzorce językowe tworzą alternatywne ścieżki synaptyczne w korze czołowej, stopniowo osłabiając stare schematy przez brak użycia.',
    lifehack: 'Przepisz jedno bolesne wspomnienie z trzeciej osoby, jakbyś opowiadał historię komuś obcemu. Dystans językowy zmienia perspektywę.'
  },
  {
    id: 'm6-m7-flow',
    from: 'm6',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Ślad Ruchowy',
    description: 'Po godzinie biegu czujesz lekki ból w nogach, przyspieszone tętno i falę ciepła w całym ciele. Każde działanie fizyczne zostawia ślad w odczuciach cielesnych.',
    psychology: 'Biofeedback ruchowy: aktywność fizyczna zmienia odczucia z ciała szybciej i bardziej namacalnie niż jakakolwiek interwencja słowna.',
    philosophy: 'Merleau-Ponty: ciało w ruchu jest ciałem przeżywającym. Działanie nie tylko zmienia świat, ale zmienia odczuwanie siebie.',
    science: 'Aktywność mięśni generuje proprioceptywne sygnały do kory czuciowej (S1) i wyzwala wyrzut endorfin, enkefelin i anandamidu.',
    lifehack: 'Gdy czujesz się odcięty od ciała albo zdrętwiały emocjonalnie, zrób 30 sekund intensywnego ruchu. Ciało natychmiast się odezwie.'
  },
  {
    id: 'm6-m8-flow',
    from: 'm6',
    to: 'm8',
    type: 'flow',
    direction: 'to',
    label: 'Dowód Empiryczny',
    description: 'Myślałeś, że nie dasz rady poprowadzić prezentacji, ale poprowadziłeś i ludzie klaskali. Twoje przekonanie o nieudolności właśnie dostało cios w szczękę od rzeczywistości.',
    psychology: 'Eksperymenty behawioralne w CBT. Terapeuta celowo zachęca do podjęcia działania, by klient sam zobaczył, że katastroficzny scenariusz się nie sprawdził.',
    philosophy: 'Pragmatyzm Peirce a: prawda testowana w działaniu, nie w teorii. Czyn jest jedynym arbitrem przekonań.',
    science: 'Błąd predykcji dopaminergicznej: gdy wynik jest lepszy niż oczekiwano, sygnał z VTA koryguje model predykcyjny w korze czołowej.',
    lifehack: 'Prowadź dziennik eksperymentów: zapisz czego się boisz, zrób to, zapisz co się naprawdę stało. Dowody rozbijają schematy.'
  },
  {
    id: 'm6-m9-flow',
    from: 'm6',
    to: 'm9',
    type: 'flow',
    direction: 'to',
    label: 'Rzeźbienie Otoczenia',
    description: 'Sprzątasz pokój i nagle czujesz, że lepiej myślisz. Budujesz biurko pod oknem i masz więcej energii do pracy. Twoje zachowania fizycznie rzeźbią otoczenie.',
    psychology: 'Behawioralna modyfikacja środowiska: aktywne kształtowanie otoczenia jako forma profilaktyki psychicznej.',
    philosophy: 'Marksowski praxis: człowiek tworzy siebie przez pracę nad materią. Nie jesteś biernym mieszkańcem świata, lecz jego rzeźbiarzem.',
    science: 'Porządek wizualny w otoczeniu obniża poziom kortyzolu i zmniejsza obciążenie poznawcze (cognitive load) kory czołowej.',
    lifehack: 'Zacznij od jednego kawałka przestrzeni: oczyść biurko do zera. Porządek na biurku działa jak reset na umysł.'
  },
  {
    id: 'm6-m11-flow',
    from: 'm6',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Zmiana Biochemii Czynem',
    description: 'Trzydzieści minut biegu zmienia Twój skład krwi bardziej niż godzina medytacji. Zjedzenie porządnego obiadu napełnia mózg glukozą. Zachowania są najbardziej bezpośrednim narzędziem zmiany biochemii.',
    psychology: 'Aktywacja behawioralna (Behavioral Activation): w depresji nie czekaj na motywację, zacznij od działania, a biochemia sama się poprawi.',
    philosophy: 'Materializm praktyczny: duch zmienia się przez pracę ciała, a nie przez kontemplację.',
    science: 'Wysiłek fizyczny zwiększa syntezę BDNF (czynnika neurotroficznego), serotoniny i dopaminy, jednocześnie obniżając markery zapalne IL-6 i TNF-alfa.',
    lifehack: 'Gdy czujesz się fatalnie i nic nie pomaga, zrób jedną z trzech rzeczy: zjedz porządny posiłek, przespaceruj się 20 minut albo idź spać. Biochemia reaguje na czyny.'
  },
  {
    id: 'm6-m13-flow',
    from: 'm6',
    to: 'm13',
    type: 'flow',
    direction: 'to',
    label: 'Akt Relacyjny',
    description: 'Przytulenie kogoś, podanie mu herbaty w trudnym momencie albo po prostu siedzenie obok w ciszy. To nie myśli ani słowa budują relacje. To konkretne czyny.',
    psychology: 'Teoria przywiązania Bowlby ego: bezpieczne przywiązanie buduje się przez powtarzalne, responsywne zachowania opiekuna wobec dziecka.',
    philosophy: 'Buberowska relacja Ja-Ty realizuje się w czynie, nie w intencji. Miłość bez gestu jest abstrakcją.',
    science: 'Fizyczny dotyk i bliskość wyzwalają wyrzut oksytocyny i wazopresyny, wzmacniając obwody przywiązania w jądrze półleżącym.',
    lifehack: 'Zamiast mówić bliskiej osobie, że Ci na niej zależy, zrób coś konkretnego: przynieś kawę, pomasuj ramiona, wyłącz telefon przy rozmowie.'
  },
  {
    id: 'm7-m3-flow',
    from: 'm7',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Interocepcja Poznawcza',
    description: 'Gdy boli Cię głowa, automatycznie zaczynasz myśleć o guzie mózgu. Gdy masz pełno energii, myślisz, że zdobędziesz świat. Ciało podpowiada tematy myślom.',
    psychology: 'Teoria konstruowanych emocji Lisy Feldman Barrett: mózg interpretuje sygnały z ciała i automatycznie dorabia do nich narrację poznawczą.',
    philosophy: 'Nietzsche: ciało jest wielkim rozumem, a mały rozum (intelekt) jest tylko jego narzędziem i zabawką.',
    science: 'Kora wyspy (insula) przekształca sygnały interoceptywne w predykcje, które kora czołowa konwertuje na treść myśli.',
    lifehack: 'Gdy nachodzą Cię czarne myśli, zanim zaczniesz je analizować, sprawdź: co mówi ciało? Może po prostu nie jadłeś 6 godzin.'
  },
  {
    id: 'm9-m3-flow',
    from: 'm9',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Pożywka Myślowa',
    description: 'Siedzisz w bałaganie i myślisz o chaosie. Patrzysz na góry i myślisz o wolności. Otoczenie non-stop dostarcza klocki, z których Twój umysł buduje narracje.',
    psychology: 'Priming środowiskowy: bodźce w otoczeniu automatycznie aktywują powiązane koncepty w umyśle, kierując strumieniem myśli bez wiedzy osoby.',
    philosophy: 'Determinizm kontekstualny: nie myślimy w próżni, lecz zawsze w odpowiedzi na to, co nas otacza.',
    science: 'Bodźce wzrokowe i słuchowe aktywują sieci asocjacyjne w korze skroniowej i ciemieniowej, automatycznie dostarczając materiał do procesów myślowych w PFC.',
    lifehack: 'Zmień otoczenie, gdy chcesz zmienić myślenie. Idź do kawiarni, do parku albo po prostu usiądź w innym pokoju. Nowe bodźce to nowe myśli.'
  },
  {
    id: 'm9-m4-flow',
    from: 'm9',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Nastrojenie Przestrzenne',
    description: 'Wchodzisz do katedry i czujesz spokój. Wchodzisz do zatłoczonego metra i czujesz napięcie. Przestrzeń nastrajała ludzkie emocje na tysiąclecia przed wynalezieniem psychoterapii.',
    psychology: 'Psychologia środowiskowa: Roger Ulrich udowodnił, że nawet widok zieleni z okna szpitala przyspiesza zdrowienie i obniża zapotrzebowanie na środki przeciwbólowe.',
    philosophy: 'Genius loci: duch miejsca. Starożytni wiedzieli, że przestrzenie mają zdolność kształtowania stanów wewnętrznych.',
    science: 'Jasne, przestronne wnętrza zwiększają syntezę serotoniny, podczas gdy ciasne, ciemne przestrzenie podnoszą bazowy poziom kortyzolu.',
    lifehack: 'Gdy czujesz się przytłoczony, wyjdź na otwartą przestrzeń. Dosłownie. Horyzont i niebo fizycznie obniżają napięcie w układzie nerwowym.'
  },
  {
    id: 'm9-m13-flow',
    from: 'm9',
    to: 'm13',
    type: 'flow',
    direction: 'to',
    label: 'Sąsiedztwo Relacyjne',
    description: 'Nie możesz zbudować głębokiej relacji z kimś, kogo nie ma w Twoim zasięgu fizycznym. Otoczenie determinuje, z kim w ogóle masz szansę się połączyć.',
    psychology: 'Efekt bliskości (Proximity Effect) w psychologii społecznej: fizyczna odległość jest jednym z najsilniejszych predyktorów powstawania relacji.',
    philosophy: 'Heideggerowski Mitsein (bycie-z): nie wybieramy relacji w abstrakcji, lecz z puli osób, które los umieścił w naszym otoczeniu.',
    science: 'Częstość kontaktu wzrokowego i fizycznej bliskości zwiększa wyrzut oksytocyny i obniża reaktywność ciała migdałowatego wobec danej osoby.',
    lifehack: 'Jeśli chcesz budować bliższe relacje z kimś, zwiększ częstość fizycznych spotkań. Nie ma skrótu. Ekrany nie wyzwalają oksytocyny.'
  },
  {
    id: 'm10-m13-flow',
    from: 'm10',
    to: 'm13',
    type: 'flow',
    direction: 'to',
    label: 'Komunikacja Relacyjna',
    description: 'Jedno niefortunne słowo potrafi zniszczyć relację budowaną latami. Jedno właściwe zdanie potrafi rozpuścić wieloletnią urazę. Język to tkanka, z której szyte są relacje.',
    psychology: 'Cztery Jeźdźcy Apokalipsy Johna Gottmana: krytyka, pogarda, defensywność i wycofanie to wzorce językowe, które niszczą związki z 93% trafnością predykcji.',
    philosophy: 'Habermasowska etyka dyskursu: autentyczna relacja wymaga komunikacji wolnej od przemocy i manipulacji.',
    science: 'Ton głosu i dobór słów modulują aktywność ciała migdałowatego u odbiorcy. Słowa nacechowane pogardą wywołują reakcję stresową identyczną z fizycznym zagrożeniem.',
    lifehack: 'Zamień zdania zaczynające się od Ty zawsze... na Ja czuję, kiedy... Jedno słowo zmienia komunikat z ataku na informację.'
  },
  // === MODERATE LINKS (18) ===
  {
    id: 'm13-m1-awareness',
    from: 'm13',
    to: 'm1',
    type: 'awareness',
    direction: 'to',
    label: 'Lustro Relacyjne',
    description: 'Ktoś zadaje Ci pytanie, na które nie znasz odpowiedzi, i nagle widzisz siebie z boku. Druga osoba działa jak lustro, w którym zauważasz rzeczy niewidoczne, gdy jesteś sam.',
    psychology: 'Relacyjna funkcja świadka (Witnessing) w terapii. Obecność drugiego człowieka aktywuje metapoznanie, którego nie osiągniesz w izolacji.',
    philosophy: 'Sartre owskie spojrzenie Innego: uświadamiamy sobie siebie w pełni dopiero wtedy, gdy ktoś na nas patrzy.',
    science: 'Kontakt społeczny aktywuje korę przyśrodkową (mPFC) i połączenie skroniowo-ciemieniowe (TPJ), odpowiedzialne za samoświadomość i teorię umysłu.',
    lifehack: 'Gdy czujesz się zagubiony, porozmawiaj z kimś zaufanym. Nie po radę, lecz po perspektywę. Samo mówienie na głos przy świadku uruchamia wgląd.'
  },
  {
    id: 'm13-m2-flow',
    from: 'm13',
    to: 'm2',
    type: 'flow',
    direction: 'to',
    label: 'Partner Odpowiedzialności',
    description: 'Dużo łatwiej wstać na trening o szóstej rano, gdy wiesz, że ktoś czeka na Ciebie pod siłownią. Obecność drugiego człowieka wzmacnia wolę, bo dodaje zewnętrzną stawkę.',
    psychology: 'Accountability Partnership: badania nad zmianą zachowań pokazują, że zobowiązanie wobec drugiej osoby zwiększa szansę na dotrzymanie postanowienia o 65%.',
    philosophy: 'Levinasowska odpowiedzialność przed twarzą Innego: obecność drugiego nakłada na nas zobowiązanie, którego nie jesteśmy w stanie nałożyć sami na siebie.',
    science: 'Świadomość obserwacji społecznej zwiększa aktywność grzbietowej kory przedczołowej (dlPFC) i obniża impulsywność mierzoną testami Go/No-Go.',
    lifehack: 'Znajdź jedną osobę do wzajemnego rozliczania. Codziennie rano wyślijcie sobie nawzajem jednozdaniowy plan dnia.'
  },
  {
    id: 'm13-m3-flow',
    from: 'm13',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Ruminacje Relacyjne',
    description: 'Pokłóciłeś się z kimś bliskim i teraz odtwarzasz tę rozmowę w głowie setny raz, wymyślając lepsze riposty. Relacje potrafią zająć całą przepustowość myśli.',
    psychology: 'Ruminacja interpersonalna: nawracające myśli o relacjach i interakcjach społecznych są jednym z najczęstszych typów ruminacji u dorosłych.',
    philosophy: 'Hegel: świadomość kształtuje się w dialektyce z innym. Myśli o ludziach to nie przerywnik, lecz rdzeń ludzkiego myślenia.',
    science: 'Sieć Wzbudzeń Podstawowych (DMN) w dużej mierze przetwarza treści społeczne i relacyjne, co tłumaczy dlaczego błądzące myśli tak często dotyczą ludzi.',
    lifehack: 'Gdy łapiesz się na powtarzaniu kłótni w głowie, zapisz ją na kartce w trzech zdaniach. Mózg puszcza ruminację, gdy czuje, że sprawa jest zabezpieczona na papierze.'
  },
  {
    id: 'm13-m6-override',
    from: 'm13',
    to: 'm6',
    type: 'override',
    direction: 'to',
    label: 'Presja Konformizmu',
    description: 'W towarzystwie nieświadomie zmieniasz sposób mówienia, chodzenia, a nawet jedzenia. Obecność innych ludzi nadpisuje Twoje indywidualne wzorce zachowania.',
    psychology: 'Eksperymenty konformizmu Solomona Ascha: nawet inteligentni ludzie zmieniają oczywistą odpowiedź pod wpływem grupy.',
    philosophy: 'Heideggerowski das Man: w trybie codzienności zachowujemy się tak jak się zachowuje, a nie tak jak chcemy.',
    science: 'Neurony lustrzane w korze przedruchowej automatycznie kopiują wzorce motoryczne obserwowanych osób, zmieniając zachowanie bez udziału świadomości.',
    lifehack: 'Dobieraj otoczenie ludzi tak samo starannie, jak dobierasz dietę. Automatycznie stajesz się średnią pięciu osób, z którymi spędzasz najwięcej czasu.'
  },
  {
    id: 'm13-m8-flow',
    from: 'm13',
    to: 'm8',
    type: 'flow',
    direction: 'to',
    label: 'Lustra Społeczne',
    description: 'Gdy ważni dla Ciebie ludzie powtarzają, że jesteś zdolny, zaczynasz w to wierzyć. Gdy powtarzają, że jesteś beznadziejny, też zaczynasz w to wierzyć. Relacje budują przekonania o sobie.',
    psychology: 'Teoria lustrzanego ja (Looking-Glass Self) Charlesa Cooleya: nasze przekonania o sobie są w dużej mierze odbiciem tego, jak widzą nas inni.',
    philosophy: 'Heglowskie uznanie: jaźń potrzebuje drugiej jaźni, by w ogóle mogła się ukonstytuować.',
    science: 'Powtarzany feedback społeczny wzmacnia ścieżki synaptyczne kodujące samoocenę w przyśrodkowej korze przedczołowej (mPFC).',
    lifehack: 'Zrób audyt otoczenia: kto regularnie mówi Ci, kim jesteś? Czy te lustra pokazują prawdę, czy zniekształconą wersję?'
  },
  {
    id: 'm13-m11-flow',
    from: 'm13',
    to: 'm11',
    type: 'flow',
    direction: 'to',
    label: 'Oksytocyna Relacyjna',
    description: 'Przytulenie bliskiej osoby dosłownie zmienia skład Twojej krwi. Samotność robi to samo, ale w drugą stronę, podnosząc stan zapalny i kortyzol.',
    psychology: 'Neuronaukowe badania Johna Cacioppo nad samotnością: chroniczna izolacja społeczna jest tak samo szkodliwa dla zdrowia jak palenie 15 papierosów dziennie.',
    philosophy: 'Arystoteles: człowiek jest z natury zwierzęciem społecznym. Poza relacjami jest albo bogiem, albo bestią.',
    science: 'Bliski kontakt fizyczny wyzwala oksytocynę z przysadki mózgowej, obniża kortyzol i markery zapalne (CRP, IL-6).',
    lifehack: 'Jeśli czujesz się chronicznie wyczerpany i nie wiesz dlaczego, policz godziny fizycznego kontaktu z ludźmi w ostatnim tygodniu. Izolacja drenuje biochemię.'
  },
  {
    id: 'm7-m2-conflict',
    from: 'm7',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Wyczerpanie Cielesne Woli',
    description: 'Gdy boli Cię głowa tak mocno, że ledwo widzisz, żadna siła woli na świecie nie zmusi Cię do skończenia raportu. Ciało potrafi kompletnie wyłączyć wolę.',
    psychology: 'Somatyczne wyczerpanie zasobów wykonawczych. Ból i zmęczenie fizyczne konsumują te same zasoby poznawcze, które potrzebne są do samokontroli.',
    philosophy: 'Schopenhauer: wola jest ślepa i potężna, ale operuje w granicach, które wyznacza ciało.',
    science: 'Sygnały bólowe z rdzenia kręgowego priorytetowo zajmują zasoby kory przedczołowej, odciągając je od funkcji wykonawczych.',
    lifehack: 'Nie walcz z ciałem siłą woli. Najpierw rozwiąż problem fizyczny: weź prysznic, połknij ibuprofen, prześpij się godzinę. Potem wracaj do pracy.'
  },
  {
    id: 'm7-m5-flow',
    from: 'm7',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Głód Rodzi Impuls',
    description: 'Burczenie w brzuchu natychmiast wyzwala ochotę na jedzenie. Naprężone mięśnie po siedzeniu wyzwalają chęć rozciągnięcia się. Ciało nie prosi, ciało żąda.',
    psychology: 'Popędowość somatyczna: sygnały z ciała tworzą podłoże dla impulsów, które umysł jedynie racjonalizuje po fakcie.',
    philosophy: 'Hobbesiański conatus: ciało jako źródło pierwotnych popędów, które rozum może co najwyżej kanalizować.',
    science: 'Spadek glukozy aktywuje podwzgórze boczne, które wysyła do kory orbitofrontalnej sygnał nagrody za jedzenie.',
    lifehack: 'Zanim ulegniesz nagłemu impulsowi, sprawdź status ciała: kiedy ostatnio jadłeś, piłeś wodę, ruszałeś się? Często impuls to zamaskowana potrzeba fizyczna.'
  },
  {
    id: 'm7-m6-flow',
    from: 'm7',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Fizyczne Wymuszenie',
    description: 'Gdy kolana się uginają ze zmęczenia, kładziesz się, nawet jeśli miałeś plan pracy do północy. Ciało wymusza zachowania bez pytania o zgodę.',
    psychology: 'Automatyczne zachowania ochronne: organizm przełącza się na tryb przetrwania, gdy obciążenie fizyczne przekracza próg tolerancji.',
    philosophy: 'Nietzscheański wielki rozum ciała: ciało ma własną logikę i własne rozkazy, których intelekt jest jedynie wykonawcą.',
    science: 'Akumulacja adenozyny w mózgu (naturalny produkt uboczny aktywności neuronalnej) aktywuje mechanizm wymuszania snu przez jądra regulujące czuwanie.',
    lifehack: 'Nie ignoruj sygnałów fizycznego wyczerpania. Praca na wymuszonej energii generuje dług metaboliczny, który wraca ze zdwojoną siłą.'
  },
  {
    id: 'm5-m1-conflict',
    from: 'm5',
    to: 'm1',
    type: 'conflict',
    direction: 'to',
    label: 'Destrukcja Obserwatora',
    description: 'Kiedy impuls jest wystarczająco silny, znika jakakolwiek zdolność patrzenia na siebie z boku. Działasz na autopilocie i dopiero po fakcie myślisz: co ja właśnie zrobiłem?',
    psychology: 'Utrata kontroli impulsywnej: intensywny impuls zawęża pole świadomości, eliminując perspektywę meta-poznawczą.',
    philosophy: 'Platońska metafora rydwanu: gdy konie (impulsy) szaleją, woźnica (obserwator) traci lejce.',
    science: 'Masywny wyrzut dopaminy w prążkowiu dezaktywuje przyśrodkową korę przedczołową odpowiedzialną za samoświadomość.',
    lifehack: 'Przed sytuacjami, w których wiesz, że impulsy są silne, ustaw z góry fizyczne bariery: oddaj kartę kredytową, wyjdź z pokoju, wyłącz aplikację.'
  },
  {
    id: 'm5-m3-flow',
    from: 'm5',
    to: 'm3',
    type: 'flow',
    direction: 'to',
    label: 'Racjonalizacja Impulsu',
    description: 'Chcesz kupić niepotrzebną rzecz i natychmiast Twój umysł zaczyna wytwarzać powody, dlaczego to świetna inwestycja. Impuls przychodzi pierwszy, a logika jest tylko jego adwokatem.',
    psychology: 'Racjonalizacja motywowana (Motivated Reasoning): umysł generuje argumenty nie po to, by dotrzeć do prawdy, ale by uzasadnić już podjętą emocjonalną decyzję.',
    philosophy: 'Hume: rozum jest i powinien być jedynie sługą namiętności. Logika nie rządzi, logika obsługuje.',
    science: 'Aktywacja prążkowia (chcenie) poprzedza aktywację kory czołowej (uzasadnienie), co widać w badaniach fMRI z opóźnieniem 200-500 ms.',
    lifehack: 'Gdy łapiesz się na gorączkowym szukaniu powodów, żeby coś zrobić, zapytaj: czy te argumenty pojawiły się PRZED ochotą czy PO niej?'
  },
  {
    id: 'm5-m4-flow',
    from: 'm5',
    to: 'm4',
    type: 'flow',
    direction: 'to',
    label: 'Frustracja Niespełnienia',
    description: 'Chciałeś zjeść to ciastko, ale się powstrzymałeś, i teraz czujesz irytację i frustrację. Zablokowany impuls nie znika: zamienia się w emocję.',
    psychology: 'Hipoteza frustracji-agresji Dollarda: zablokowany popęd generuje frustrację, która szuka ujścia w emocji lub zachowaniu agresywnym.',
    philosophy: 'Freudowska ekonomia libidinalna: zablokowana energia popędowa musi znaleźć ujście, bo nie może po prostu zniknąć.',
    science: 'Zahamowanie odpowiedzi motorycznej przy wysokim pobudzeniu dopaminowym generuje sygnał błędu w przednim zakręcie obręczy (ACC), odczuwany jako frustracja.',
    lifehack: 'Gdy po powstrzymaniu impulsu czujesz narastającą irytację, nie walcz z nią. Skieruj tę energię w działanie fizyczne: spacer, przysiady, sprzątanie.'
  },
  {
    id: 'm5-m7-flow',
    from: 'm5',
    to: 'm7',
    type: 'flow',
    direction: 'to',
    label: 'Somatyka Impulsu',
    description: 'Gdy nachodzi Cię silna ochota na coś zakazanego, serce przyspiesza, dłonie się pocą, mięśnie napinają. Impuls to nie abstrakcyjna myśl: to fizyczne przygotowanie ciała do akcji.',
    psychology: 'Somatyczne markery impulsu (Damasio): ciało przygotowuje się do działania, zanim umysł podjął świadomą decyzję.',
    philosophy: 'Spinozjański conatus: dążenie do przetrwania i przyjemności wyraża się jednocześnie jako psychiczna chęć i fizyczne napięcie.',
    science: 'Aktywacja układu współczulnego przez podwzgórze: wzrost tętna, rozszerzenie źrenic i napięcie mięśni szkieletowych w ramach przygotowania do akcji.',
    lifehack: 'Zauważ, gdzie w ciele czujesz impuls: żołądek, klatka piersiowa, ręce? Samo skierowanie uwagi na to miejsce aktywuje korę wyspy i włącza hamulce.'
  },
  {
    id: 'm6-m2-flow',
    from: 'm6',
    to: 'm2',
    type: 'flow',
    direction: 'to',
    label: 'Wzmocnienie lub Osłabienie Woli',
    description: 'Każdy mały sukces dodaje Ci wiary, że potrafisz kontrolować swoje życie. Każda porażka ją odbiera. Wola nie jest stała: karmi się lub głodzi wynikami Twoich działań.',
    psychology: 'Pętla wzmocnienia w teorii społeczno-poznawczej Bandury: sukces behawioralny zwiększa poczucie sprawczości, a porażka je obniża.',
    philosophy: 'Nietzscheańska wola mocy: wola rośnie przez ćwiczenie w działaniu, a więdnie przez bezczynność.',
    science: 'Sygnały nagrody z VTA po udanym działaniu wzmacniają ścieżki dopaminergiczne do kory przedczołowej, ułatwiając przyszłą inicjację działań.',
    lifehack: 'Celowo planuj mikro-zwycięstwa: pościel łóżko rano, zrób 10 przysiadów, wyślij jeden trudny e-mail. Seria drobnych sukcesów ładuje baterię woli na resztę dnia.'
  },
  {
    id: 'm8-m5-flow',
    from: 'm8',
    to: 'm5',
    type: 'flow',
    direction: 'to',
    label: 'Impuls z Przekonania',
    description: 'Wierzysz, że zasługujesz na nagrodę po ciężkim dniu, i natychmiast rodzi się impuls sięgnięcia po alkohol, zakupy albo fast food. Przekonanie daje impulsowi legitymację.',
    psychology: 'Permissive beliefs w terapii uzależnień: przekonania udzielające pozwolenia (permission-giving thoughts) obniżają barierę dla impulsywnych zachowań.',
    philosophy: 'Akrazja u Arystotelesa: wiemy, że coś jest złe, ale wewnętrzna narracja daje nam wymówkę do ulegania.',
    science: 'Aktywacja korowych reprezentacji przekonania o zasłużonej nagrodzie pobudza szlak nagrody w jądrze półleżącym.',
    lifehack: 'Złap zdanie zasługuję na... i zapytaj: czy to jest potrzeba czy wymówka? Prawdziwa potrzeba ma alternatywy. Wymówka prowadzi zawsze w to samo miejsce.'
  },
  {
    id: 'm9-m2-conflict',
    from: 'm9',
    to: 'm2',
    type: 'conflict',
    direction: 'to',
    label: 'Otoczenie Wspierające lub Niszczące Wolę',
    description: 'W cichym, uporządkowanym pokoju potrafisz pracować godzinami. W chaotycznym, hałaśliwym otoczeniu nie jesteś w stanie skupić się na pięć minut. Otoczenie wzmacnia lub demoluje Twoją wolę.',
    psychology: 'Obciążenie poznawcze ze środowiska (Environmental Cognitive Load): każdy bodziec w otoczeniu pochłania kawałek zasobów kory czołowej.',
    philosophy: 'Determinizm środowiskowy: warunki zewnętrzne nie tylko wpływają na wolę, lecz wyznaczają jej operacyjne granice.',
    science: 'Hałas powyżej 65 dB podnosi poziom kortyzolu i osłabia funkcje wykonawcze mierzone testami Stroopa i N-back.',
    lifehack: 'Zainwestuj w słuchawki z aktywnym tłumieniem hałasu. To jedna z najbardziej opłacalnych inwestycji w Twoją produktywność.'
  },
  {
    id: 'm11-m1-conflict',
    from: 'm11',
    to: 'm1',
    type: 'conflict',
    direction: 'to',
    label: 'Metaboliczna Śmierć Obserwatora',
    description: 'Po nieprzespanej nocy nie jesteś w stanie obserwować samego siebie z dystansu. Reagujesz automatycznie na każdy bodziec. Świadomość potrzebuje paliwa tak samo jak mięśnie.',
    psychology: 'Deprywacja snu i utrata metapoznania: badania Matthew Walkera pokazują, że brak snu obniża zdolność do samoobserwacji do poziomu porównywalnego z intoksykacją alkoholową.',
    philosophy: 'Materialny warunek ducha: świadomość nie jest czymś, co mamy niezależnie od ciała, lecz funkcją sprawnie działającego organizmu.',
    science: 'Deprywacja snu obniża łączność funkcjonalną między korą przedczołową a korą wyspy, wyłączając obwody samoświadomości.',
    lifehack: 'Traktuj 7 godzin snu jak niepodlegającą dyskusji inwestycję. Każda godzina mniej to mierzalny spadek zdolności do autorefleksji.'
  },
  {
    id: 'm11-m6-flow',
    from: 'm11',
    to: 'm6',
    type: 'flow',
    direction: 'to',
    label: 'Energetyczna Zdolność do Działania',
    description: 'Nie możesz biegać bez glukozy w mięśniach. Nie możesz myśleć bez glukozy w mózgu. Biochemia wyznacza twardy limit tego, ile jesteś w stanie zrobić.',
    psychology: 'Model zasobowy (Resource Model) w psychologii zdrowia: każde zachowanie wymaga metabolicznego paliwa i nie istnieje nieograniczona produktywność.',
    philosophy: 'Materializm biologiczny: zamiary ducha są piękne, ale bez sprawnego ciała pozostają abstrakcjami.',
    science: 'ATP (adenozynotrójfosforan) jest walutą energetyczną każdej akcji, od skurczu mięśnia po potencjał czynnościowy w neuronie.',
    lifehack: 'Przed wymagającym zadaniem zjedz posiłek bogaty w białko i złożone węglowodany. Nie zaczynaj maratonu na pustym baku.'
  }
];

export const MAKRO_NODES: DomainNode[] = [
  {
    id: "ma1",
    title: "Fundament Biologiczny",
    description: "Nasz fizyczny punkt wyjścia. Zestaw genów, organizm i narządy, które mocno dyktują nasze bazowe możliwości.",
    psychology: "Nasze mózgi ewolucyjnie to nadal mózgi łowców-zbieraczy, które gubią się w nowoczesności, co psychiatria nazywa zaburzeniami lękowymi.",
    philosophy: "Ciało to nasz kotwica. Jesteśmy bezwzględnie podlegli biologii ewolucyjnej, zmęczeniu i upływowi czasu.",
    science: "Geny decydują o wrażliwości na kortyzol. Telomery o czasie życia. Wrodzony hardware naszej maszyny.",
    lifehack: "Nie naprawiaj psychiki, dopóki nie sprawdzisz biologii. Raz w roku rób panel badań fizjologicznych.",
    group: 'physiological'
  },
  {
    id: "ma2",
    title: "Środowisko Geograficzne",
    description: "Klimat, miasto lub wieś. Betonoza czy zieleń. Twarde fizyczne parametry Twojego życia.",
    psychology: "Brak kontaktu z zielenią i zatłoczenie to stały stresor wywołujący agresję i zmęczenie uwagowe.",
    philosophy: "Determinizm geograficzny dowodził, że warunki terenowe wręcz kształtują prawa i obyczaje ludzkie.",
    science: "Zanieczyszczenie powierza i brak światła drastycznie modulują układ odpornościowy i syntezę witamin.",
    lifehack: "Przestrzeń kształtuje psychikę. Reguluj światło, unikaj hałasu ulicy w sypialni, uciekaj w zieleń.",
    group: 'environmental'
  },
  {
    id: "ma3",
    title: "Nieświadomość i Obrona",
    description: "Wyparte emocje i wspomnienia, których wolimy nie dostrzegać, oraz sprytne wymówki chroniące nasze ego.",
    psychology: "Zjawisko Cienia (C.G. Jung). Uciekanie od własnej agresji przez rzutowanie jej (projekcję) na otoczenie.",
    philosophy: "Obnażenie iluzji ludzkiej racjonalności. Ludźmi rządzą potężne pędy, do których intelekt tylko szuka wymówek.",
    science: "Potencjał gotowości powstaje w pniu mózgu przed świadomą decyzją. Mózg ukrywa przed nami większość swojej pracy.",
    lifehack: "Audyt irytacji. 'Jaki wyparty aspekt mojego cienia odzwierciedla człowiek, który doprowadza mnie do szału?'.",
    group: 'cognitive'
  },
  {
    id: "ma4",
    title: "Pamięć Somatyczna (Trauma)",
    description: "Zapisane w mięśniach i powięziach ślady po ogromnym stresie z przeszłości, który nie został uregulowany.",
    psychology: "Ekstremalny lęk zamraża się w ciele (Bessel van der Kolk). Objawia się ciągłym trybem walki bez wyraźnego powodu.",
    philosophy: "Przeszłość nie mija (Bergson) - wnika w teraźniejszość, bezustannie koloryzując to, jak odbieramy chwilę obecną.",
    science: "Trauma wyłącza hipokamp (rejestrator czasu), a aktywuje ciało migdałowate. Wtedy lęk jest przeżywany, a nie tylko wspominany.",
    lifehack: "Manualne uwalnianie powięzi. Rutyny TRE czy odpowiedni masaż zrzucają z ciała zgromadzone mechaniczne napięcie.",
    group: 'physiological'
  },
  {
    id: "ma5",
    title: "Matryca Systemowa",
    description: "Bagaż rodzinny. Niewidzialne zasady, role (bohater, kozioł ofiarny) przekazywane przez drzewo genealogiczne.",
    psychology: "Terapia systemowa dowodzi, że problem jednostki to tylko wyraz problemu całej nierozwiązanej struktury rodzinnej.",
    philosophy: "Relacje władzy, historia i uwarunkowania determinują to, na ile możemy w ogóle uznać się za niezależne jednostki.",
    science: "Pierwsze miesiące z opiekunami kalibrują nerw błędny i poziomy oksytocyny - to fundament przywiązania.",
    lifehack: "Genogram uświadomiony. Wypisz destrukcyjne tradycje Twojego rodu i świadomie je odrzuć.",
    group: 'environmental'
  },
  {
    id: "ma6",
    title: "Matryca Językowa (Membrana)",
    description: "Zbiór pojęć, metafor i konstrukcji. To przez nie interpretujesz swoje życie i cierpienie.",
    psychology: "Kultura i język zawężają zakres akceptowalnych zachowań. Nie czujemy tego, czego nie potrafimy nazwać.",
    philosophy: "Język to dom bycia. Tworzy sferę wokół nas (membranę), oddzielając nasz rdzeń od surowej, niewyrażalnej zewnętrzności.",
    science: "Neurolingwistyka pokazuje, że gramatyka wpływa na kategoryzowanie zdarzeń i postrzeganie winy.",
    lifehack: "Zmień główne metafory. Gdy życie to 'poligon', podświadomość wchodzi w wieczny tryb oblężenia.",
    group: 'cognitive'
  },
  {
    id: "ma7",
    title: "Kryzysy Rozwojowe",
    description: "Naturalne, bolesne momenty przejścia do następnego etapu dojrzałości. Rozpad starego układu.",
    psychology: "Erik Erikson opisał osiem kryzysów w życiu człowieka. Ominięcie choćby jednego prowadzi do ciężkiej stagnacji w dorosłości.",
    philosophy: "Dialektyka rozwoju. Stara teza musi ulec rozbiciu, by pojawiła się nowsza, silniejsza synteza. Rozpacz to punkt zwrotny.",
    science: "Zsynchronizowane z gigantycznym przycinaniem synaptycznym (np. u nastolatków kora mózgowa przebudowuje się z chaosu).",
    lifehack: "Sprawdź, na jakim etapie kryzysu dekady jesteś. To zdejmuje lęk, bo uświadamia, że ten proces jest naturalny.",
    group: 'cognitive'
  },
  {
    id: "ma8",
    title: "Zeitgeist (Duch Czasu)",
    description: "Panujące w Twojej epoce mody, narracje o sukcesie i zbiorowe lęki. Powietrze socjologiczne, którym oddychasz.",
    psychology: "Współczesne media pompują nierealne wzorce i narcyzm. Problemy psychologiczne mocno zmieniają się z pokolenia na pokolenie.",
    philosophy: "Foucault: epoka nakłada ciche ramy na to, kto jest uważany za normalnego, a o czym w ogóle nie wolno na poważnie dyskutować.",
    science: "Memetyka i algorytmy uwagowe. Idee wirusują społeczeństwo szybciej niż choroby biologiczne.",
    lifehack: "Odetnij powiadomienia z serwisów informacyjnych. Wyrwanie się z ciągłej gorączki medialnej to zysk absolutny.",
    group: 'environmental'
  },
  {
    id: "ma9",
    title: "Wektor Egzystencjalny (Atraktor)",
    description: "Twój nadrzędny cel, sens albo misja. Grawitacyjna siła wybiegająca w przyszłość, która chroni przed pustką.",
    psychology: "Logoterapia udowadnia, że człowiek obciążony mocnym poczuciem celu zniesie każde 'jak' przeżycia. Brak 'po co' spycha w nałogi.",
    philosophy: "Zadanie wyznaczenia sensu w świecie bezwzględnej wolności (egzystencjalizm).",
    science: "Obecność celu wiąże się ze zwiększoną plastycznością przedczołową i niższym ryzkiem otępienia w podeszłym wieku.",
    lifehack: "Zrób rygorystyczny 'Test Pogrzebu'. Bolesne, ale natychmiast układa wartości życiowe w hierarchię.",
    group: 'executive'
  },
  {
    id: "ma10",
    title: "Czynnik Chaosu",
    description: "Niespodziewana losowość, czarne łabędzie, wypadki lub uśmiech losu, który brutalnie obala najtwardsze plany.",
    psychology: "Wzrost potraumatyczny. Paradoksalnie najtrudniejsze ciosy w strukturę wymuszają budowę o wiele stabilniejszej siły psychicznej.",
    philosophy: "Amor Fati - radykalna akceptacja rzeczywistości. Zdarzenia po prostu nadchodzą. To Ty nadajesz im destrukcyjne znaczenie.",
    science: "Termodynamika - żaden układ nie zachowa porządku w nieskończoność. Nie da się przewidzieć losu z powodu zbyt wielkiej liczby zmiennych.",
    lifehack: "Zawsze zachowuj margines błędu. W zasobach finansowych, emocjonalnych i czasowych licz się z anomalią.",
    group: 'awareness'
  },
  {
    id: "ma11",
    title: "Technosfera i Sieć",
    description: "Nasze zrośnięcie z technologią. Urządzenia pełniące rolę zewnętrznych pamięci i procesorów naszego mózgu.",
    psychology: "FOMO i zjawisko atrofii umiejętności koncentracji głębokiej na rzecz płytkiego skanowania informacji.",
    philosophy: "Teoria rozszerzonego umysłu. Nasz smartfon jest dziś przedłużeniem naszego ciała w takim samym sensie, jak laska dla niewidomego.",
    science: "Ciągły multitasking pije glukozę, wypalając układ nerwowy i uodparniając szlaki dopaminowe na subtelne przyjemności.",
    lifehack: "Sypialnia wolna od prądu. Telefon wymusza gotowość poznawczą; bez niego ratujesz głębokie fazy snu.",
    group: 'environmental'
  }
];

export const MAKRO_LINKS: DomainLink[] = [
  {
    id: 'ma1-ma4-flow',
    from: 'ma1',
    to: 'ma4',
    type: 'flow',
    direction: 'to',
    label: 'Pamięć Komórkowa',
    description: 'Podłoże biologiczne koduje ślady po głębokim stresie w tkankach i ekspresji genów.',
    psychology: 'Epigenetyczne zakodowanie urazu w podatności komórkowej.',
    philosophy: 'Ciało jako żywy archiwista historii gatunkowej.',
    science: 'Modyfikacja metylacji DNA pod wpływem kortyzolu.',
    lifehack: 'Dbaj o bazowy stan biologiczny, by wspomóc leczenie urazów.'
  },
  {
    id: 'ma5-ma4-flow',
    from: 'ma5',
    to: 'ma4',
    type: 'flow',
    direction: 'to',
    label: 'Dziedziczenie Traum',
    description: 'Nierozwiązany uraz rodziców przekazywany jest dzieciom przez styl wychowania i biologię.',
    psychology: 'Trauma transgeneracyjna w psychoterapii systemowej.',
    philosophy: 'Dziedziczne obciążenia rodu.',
    science: 'Wpływ stresu rodzicielskiego na rozwój układu limbicznego niemowlęcia.',
    lifehack: 'Nazwij i przerwij szkodliwy schemat, by nie przekazać go dalej.'
  },
  {
    id: 'ma5-ma3-conflict',
    from: 'ma5',
    to: 'ma3',
    type: 'conflict',
    direction: 'both',
    label: 'Współdzielony Cień',
    description: 'Rodzinne wyparcia i milczące tabu zasilają indywidualny cień psychiczny.',
    psychology: 'Cień rodzinny w analizie jungowskiej.',
    philosophy: 'Niewidzialne lojalności rodowe.',
    science: 'Wzorzec nieświadomych mikroekspresji opiekunów w dzieciństwie.',
    lifehack: 'Zbadaj co w Twojej rodzinie było tematem zakazanym.'
  },
  {
    id: 'ma2-ma1-flow',
    from: 'ma2',
    to: 'ma1',
    type: 'flow',
    direction: 'to',
    label: 'Wektor Adaptacyjny',
    description: 'Klimat i jakość otoczenia bezpośrednio modyfikują funkcjonowanie Twojego organizmu.',
    psychology: 'Wpływ środowiska geograficznego na stan psychiczny.',
    philosophy: 'Determinizm geograficzny.',
    science: 'Synteza witaminy D3 i wpływ zanieczyszczeń na układ odpornościowy.',
    lifehack: 'Spędzaj minimum 20 minut dziennie na świeżym powietrzu.'
  },
  {
    id: 'ma8-ma11-flow',
    from: 'ma8',
    to: 'ma11',
    type: 'flow',
    direction: 'both',
    label: 'Infostruktura',
    description: 'Duch epoki tworzy technologię, która z kolei redefiniuje duch czasów.',
    psychology: 'Uzależnienie od bodźców cyfrowych w nowoczesności.',
    philosophy: 'Teoria mediów McLuhana – medium jest przekazem.',
    science: 'Przebudowa szlaków dopaminowych przez algorytmy sieciowe.',
    lifehack: 'Rób cyfrowy detoks raz w tygodniu.'
  },
  {
    id: 'ma8-ma5-flow',
    from: 'ma8',
    to: 'ma5',
    type: 'flow',
    direction: 'to',
    label: 'Ewolucja Ról Społecznych',
    description: 'Normy socjologiczne danych czasów dyktują podział ról w rodzinie i grupie.',
    psychology: 'Wpływ dyskursu kulturowego na tożsamość rolizowaną.',
    philosophy: 'Foucault – władza dyskursu nad zachowaniem jednostek.',
    science: 'Presja społeczna modulująca poziom hormonów przywiązania.',
    lifehack: 'Sprawdź, które ze swoich ról przyjąłeś bezrefleksyjnie ze społeczeństwa.'
  },
  {
    id: 'ma6-ma3-conflict',
    from: 'ma6',
    to: 'ma3',
    type: 'conflict',
    direction: 'both',
    label: 'Granice Poznania',
    description: 'Język i kultura próbują schwytać w słowa nieświadome pędy, tworząc napięcie.',
    psychology: 'Symbolizacja nieświadomego w psychoanalizie.',
    philosophy: 'Wittgenstein – to o czym nie można mówić, o tym należy milczeć.',
    science: 'Sprzężenie między korą językową a strukturami głębokimi mózgu.',
    lifehack: 'Nie próbuj każdego odczucia racjonalizować słowami.'
  },
  {
    id: 'ma7-ma5-conflict',
    from: 'ma7',
    to: 'ma5',
    type: 'conflict',
    direction: 'both',
    label: 'Rozpad Lojalności',
    description: 'Dojrzewanie i kryzys indywidualny zmuszają do zakwestionowania sztywnych reguł rodowych.',
    psychology: 'Indywiduacja według Junga – wychodzenie ze skryptu rodzinnego.',
    philosophy: 'Bunt egzystencjalny przeciw tradycji.',
    science: 'Przebudowa połączeń synaptycznych w korze przedczołowej u progu dojrzałości.',
    lifehack: 'Zaakceptuj fakt, że rozwój czasem wymaga niepoprawności wobec oczekiwań innych.'
  }
];
